backend/endpoints/rom.py, backend/endpoints/scan.py, backend/handler/db_handler.py, backend/main.py, backend/utils/__init__.py, frontend/.eslintignore, frontend/.eslintrc.json, frontend/package.json, frontend/src/components/Notification.vue, frontend/src/services/download.js, frontend/src/utils/socket.js, frontend/src/views/Details.vue, frontend/src/views/Gallery.vue, frontend/src/views/library/Scan.vue
* Socket event names are now prepended with the endpoint
* `scan:scanning_platform`, `scan:done`, etc.
* Get `eslint` working with a basic config and ignore file
* Refactor the tag parser to accept common filename format
* `LEGO Batman 2 - DC Super Heroes (France) (En,Fr) (Rev 1)`
At some point I'd like to add a simple prettier config (and settle on consistent code style).
=> Refactor socket connections

backend/config/__init__.py, env.template, frontend/vite.config.js
As a Mac developer, my localhost port is already taken by Airplay Receiver ([see this link](https://apple.stackexchange.com/questions/431154/controlcenter-app-listens-to-port-5000-tcp-on-monterey-os-is-that-normal-why-d)). This PR allows for the backend port to be configurable, or to use the port 5000 as the fallback. This is handled at the Python and Vite level.
Additionally - I added support for Vite to pull in both the frontend `.env` and parent directory `.env` for future handling of custom configurations.
=> Configurable backend port

README.md
A few readme changes to better guide the user toward a successful first load: 
Updated installation section to clarify the need for the IGDB key to run the application and setting up folder structure. Failing to do these things before spinning up Romm prevents scanning from working, so they are best to handle first. Additionally, the folder structure section is updated to call the user's attention to the list of platform names and that custom names may be used in conjunction with entries in the config.yml file.
=> Update README.md - clarify installation and folder structure sections

backend/config/__init__.py, backend/endpoints/platform.py, backend/endpoints/rom.py, backend/endpoints/search.py, backend/handler/db_handler.py, backend/main.py, backend/models/rom.py, backend/utils/fs.py, frontend/package-lock.json, frontend/package.json, frontend/src/App.vue, frontend/src/components/GameDetails/BackgroundHeader.vue, frontend/src/components/GameGallery/Card/Cover.vue, frontend/src/components/GameGallery/FilterBar.vue, frontend/src/components/GameGallery/ListItem/Item.vue, frontend/src/main.js, frontend/src/services/api.js, frontend/src/utils/utils.js, frontend/src/views/Details.vue, frontend/src/views/Gallery.vue, poetry.lock, pyproject.toml
There's considerable slowdown (lag) in the app when the number of roms in a library hits 500+. This PR attempts to mitigate that issue in a couple ways.
* Introduce cursor-based pagination with [fastapi_pagination](https://uriyyo-fastapi-pagination.netlify.app/)
* Gallery view holds next cursor value and requests further entries with it
* ~~Add [axios-cache-interceptor](https://axios-cache-interceptor.js.org/) to cached cursored rom list requests~~
* Set `timestamp` on cover url when cover is updated
* This allows for cache-busting images but only when required
* Move search to backend and use rom list endpoint with `ilike` filter
* Add [lodash](https://lodash.com/) to debounce search input
* Fix accessing `file_name` when updating rom, but "Rename rom" not checked
Either already have a …
=> Pagination for large libraries

backend/endpoints/platform.py, backend/endpoints/rom.py, backend/endpoints/scan.py, backend/handler/db_handler.py, backend/utils/fastapi.py, backend/utils/tests/test_fastapi.py, frontend/src/views/Details.vue, frontend/src/views/Gallery.vue
After delete a ROM or purging the ROM list for a platform, call `update_n_roms` to update the count, based on the number of ROMs in the DB. Also refresh the platform list so the count updates (this can be improved at a later date).
Fixes #325
=> Update platform rom counts after scan/delete

backend/endpoints/scan.py, backend/handler/igdb_handler.py, backend/handler/ps2_opl_index.py, backend/handler/tests/cassettes/test_get_ps2_opl_rom.yaml, backend/handler/tests/test_igdb_handler.py, frontend/src/views/library/Scan.vue
Patches in support for the [OPL](https://github.com/ps2homebrew/Open-PS2-Loader) file naming convention. In the case where the filename start with a value matching the OPL serial regex (XXXX_000.00), use the name from the index to search IGDB. This also has the added benefit of using that name over the filename when the IGDB lookup fails.
Note: I chose to implement the index as an in-memory python dict due to it's relatively small size (1.1MB), and not having to load it in from a fixture file (JSON, YAML). In the future, objects like these can be stored in Redis to offload that memory footprint, while allowing for fast-ish access. Since you can't view it in github, here's the structure of that index:
```python
opl_index = {
"SLES_556.71": {
"Name": "Fifa '14",
"Region": "PAL"
}, …
```
=> Patch in ps2/opl support for game scanning

docker/Dockerfile, docker/init_scripts/init, docker/init_scripts/init_worker
Disable redis worker (and redis in general) for futures releases and adds netcat to base image
=> Redis worker hotfix

frontend/src/components/Dialog/EditRom.vue
After researching if a file name with slash character ('/') is possible in linux, it is not worth it the effort to make it possible, so this PR will introduce input rules when editing a rom file name:
- slash character is not allowed when renaming a rom
- file name is required qhen editing a rom, not updating it if the field is empty
Closes #348
=> Rename rom with slash

backend/handler/igdb_handler.py
For some reason an auth token I had stored in Redis expired, even though twitch says it should still be good for another ~40 days (expiry is ~60 days), which was causing requests to fail. This PR adds a 1-time catch to requests that will force-refresh the token if IGDB returns a [401 Unauthorized error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401).
Also see https://dev.twitch.tv/docs/authentication/#tokens-dont-last-forever
=> Attempt to force refresh twitch auth token if 401

backend/handler/igdb_handler.py
When the list of results is returned from IGDB search, we should prioritize results where the name (or slug) matches the search term exactly.
Related: https://github.com/zurdi15/romm/issues/285#issuecomment-1703891357
=> Return exact match first when searching roms

backend/endpoints/scan.py
Long scans were timing out since the default timeout is 5 minutes, extend it to 4 hours.
=> Set scan task timeout to 4 hours

backend/handler/igdb_handler.py, backend/handler/tests/test_igdb_handler.py, frontend/src/plugins/router.js, frontend/src/views/Gallery/Base.vue
When you navigate out of the gallery (like to the homepage) the rom store is not reset, which leads to the wrong roms being displayed when navigating to another platform gallery. This PR adds `onBeforeRouteLeave` which will a) reset the store if leaving the gallery but b) keep it and only reset selection if navigating to game details of the same platform.
Also adds another fix that stores the igdb id as an empty string when not found, instead of the string "0".
=> Clear rom store when un-mounting gallery

backend/utils/__init__.py, backend/utils/tests/conftest.py, backend/utils/tests/test_utils.py
This new regex will strip out any tags in the filename, as well as 1 (or more) file extensions. The regex is fairly aggressive, so in rare cases it will remove parts of the filename. I think this is preferred over leaving parts of the extension in the name, as manual search should still work with a shorter name, but I'd like your thoughts on the change!
You can test it on [regex101.com](https://regex101.com) with the following examples:
```
007 - Agent Under Fire.zip
007 - Agent Under Fire.nkit.iso
007 - Agent Under Fire (USA).zip
007 - Agent Under Fire [rev-1].zip
007 - Agent Under Fire [rel-3] (USA).zip
Jimmy Houston's Bass Tournament U.S.A..zip
Battle Stadium D.O.N.zip
```
=> Aggressive removal of file extensions and tags

backend/utils/fs.py, backend/utils/tests/cassettes/test_get_cover.yaml, backend/utils/tests/test_fs.py
URL encode the game title before storing under `/resources`, so the saved path only contains valid caracters.
Closes #386
=> [ROMM-386] Fix assets path for games with invalid caracters in titles

frontend/src/stores/roms.js, frontend/src/views/Gallery/Base.vue
So this is a little cleanup to the way we deal with the pinia store for roms. Essentially, anytime a change is made to the `_all` rom list, we reorder the list and remove any duplicates. This is just to make sure the list is in a healthy state in all cases.
The real fix here is adding any search results to the `_all` roms list. This way, when we set the list of filtered IDs in the `romStore`, we have the results to pull from.
Fixed #378
=> [ROMM-378] Fixes to search and pinia store

examples/docker-compose.example.yml
Current variables do not work, as mentioned here: https://github.com/zurdi15/romm/issues/394#issuecomment-1751814068
As you say, the keys will work on dev-latest. But the example file doesn't pull dev-latest, so it'd make more sense for new users if the example file used the same conventions as the release it currently pulls for the time being.
=> Change IGDB ID/SECRET variables to working names

docker/Dockerfile, docker/init_scripts/init, docker/init_scripts/init_back, docker/nginx/default.conf, poetry.lock, pyproject.toml
for kubernetes deployments and security minded folks its prefered to run containers with a readonly rootfs.
this patch changes nginx configuration in a way that it is possible to run it on such readonly instances.
(mounted volumes are by design exempt from this)
other things i changed are:
- the default listen port for nginx to not be port 80 (since that port can not be bound without root permissions)
- the connection between uvicorn and nginx was switched from using TCP to unix domain socket
- alpine base image instead of ubuntu to shave a few mb from the docker container size
- added cache cleaning for poetry
- squashed docker layers down to one as last build step to reduce final image size ( 112.32MiB   from  260.36MiB in the beginning )
=> general docker image optimization

.github/workflows/build.yml, docker/Dockerfile, docker/init_scripts/init, docker/init_scripts/init_back, docker/init_scripts/init_worker, examples/docker-compose.example.yml, poetry.lock, pyproject.toml
introduce python virtual environments so that project dependencies dont clash with the OS shipped python libraries.
As an example poetry tried to update `packaging` which is not possible since its usually shipped with the used OS distro and can not be managed by pip or poetry if installed in the OS, with venvs that limitation is solved and said package is able to be managed by the project.
with a venv we are indenpendent from what the OS shipps, even in core libraries and can update them however we want :)
i also added some meaningful comments to the dockerfile to explain what is happening
=> add venv to docker and refactor

frontend/src/stores/roms.js, frontend/src/views/Gallery/Base.vue
Cleanup the logic around resetting the gallery to catch all types of navigation events.
Fixes #408
=> [ROMM-408] Fix reset store on navigate

examples/docker-compose.example.yml, frontend/src/components/Drawer/Base.vue, frontend/src/stores/platforms.js, frontend/src/views/Dashboard/Platforms.vue, frontend/src/views/Dashboard/Summary.vue
Platforms without roms now will be hidden in the drawer and the dashboard.
Closes #396
=> [ROMM-396] Hide platforms with no roms in dashboard and drawer

.gitignore, backend/handler/igdb_handler.py, backend/tasks/update_switch_titledb.py, backend/tasks/utils.py, backend/utils/__init__.py, backend/utils/tests/test_utils.py
In #350 it was clarified that sometimes the filename will contain the `productID`, and not the `titleID`. 
* Map the `productID` to the `titleID` during async task and save result to JSON file
* Match against product ID format during scan/rescan
* Less aggressive check for multiple file extensions
=> Add check for productID in file name

backend/endpoints/rom.py, backend/handler/db_handler.py, backend/models/rom.py, frontend/src/plugins/vuetify.js, frontend/src/stores/roms.js
This PR adds a new property to `Rom` that builds the string we use to compare games when sorting them. It'll remove leading The/A/And, strip white space, and make it lowercase. We're also now using the name to compare, falling back to the filename without tags.
Closes #450 
Closes #449
=> [ROMM-450][ROMM-449] Improve rom sort order

README.md
change readme images and resources to their fully qualified URI to have the [github.io page](https://zurdi15.github.io/romm/) render and link to the correct resources (docker-compose example, images)
=> use fully qualified links in readme

docker/nginx/default.conf
bring nginx's accesslog in line with the overall romm log format
=> Nginx logformat touchup

frontend/src/components/Gallery/AppBar/ScanBtn.vue, frontend/src/views/Library/Scan/Base.vue
When we receive a webhook with a newly scanned game, add it immediately to the store so it appears in the currently selected platform library.
Closes #467
=> [ROMM-467] Add games to store on scan

backend/handler/db_handler.py, frontend/src/views/Library/Scan/Base.vue
The scan backend expects `fs_slug`, so pass that in when scanning in the `Scan` view.
=> [ROMM-501] Fix scan with folder overrides

unraid_template/romm.xml
- ports changed to 8080 instead of 80. As the Docker application runs on 8080
- The config.yml file has been deleted, as you need to specify a path and not a file, which leads to the error message "config.yml is a directory".
=> Update Undraid romm.xml

backend/endpoints/rom.py, backend/handler/igdb_handler.py, frontend/src/services/api.js
Downloading ``multi-part`` games breaks the download feature when any of the parts contains a ``comma`` in the name.
This is because the ``files`` parameter is a parsed string that is splitted. Changing that to an actual list parameter fixes this issue.
Aditionally, this PR fixes an error caused when a matched rom, searched manually into IGDB, doesn't have summary.
Closes #520
=> [ROMM-520] Fix downloading multi-file roms which filenames include comma characters

backend/endpoints/scan.py, backend/handler/igdb_handler.py, frontend/src/views/Library/Scan/Base.vue
Now users can ``rescan`` only those games that weren't identified by ``IGDB`` after some time to check if those games were added to ``IGDB``.
=> [ROMM-519] Added rescan unidentified games only feature

examples/config.example.yml
- Added some additional comments to config.example.yml to help explain the difference between single and multi part ROMs
- Added a wildcard example under `multi_part:`
=> Add additional comments to config.example.yml

backend/tasks/update_mame_xml.py
Removing the hash means we can update the file without changing the URL in the code
=> Remove file hash from mame file url

backend/config/config_loader.py, backend/models/rom.py, frontend/src/components/Details/Cover.vue, frontend/src/components/Game/Card/Cover.vue, frontend/vite.config.js
This PR stops injecting the service worker into the app, which should stop those download issues.
Also fixed cover fallback and adds validation for config.yml when mounted.
=> Disable the pwa service worker

frontend/src/App.vue, frontend/src/components/Details/ActionBar.vue, frontend/src/components/Dialog/Rom/UploadRom.vue, frontend/src/components/Gallery/FabMenu/Base.vue, frontend/src/stores/roms.ts, frontend/src/types/index.ts, frontend/src/views/Gallery/Base.vue
Scan sockets now works properly, not being stucked due to switch them off earlier than expected
It also fixed a bug where the just scanned roms are added to the gallery, independently of the platform you are. Now it only adds the rom if you are in the platform that roms belongs.
=> Fixed scan sockets

backend/alembic/versions/0014_asset_files.py
Switch to using params in execute so data does not have to be formatted/sanitized before inserting
=> [HOTFIX] Use params when running sqlite -> maria migration

docker/nginx/default.conf
When fetching static files (`/assets`), not found assets should 404 (and not return `index.html`). This will allow emulatorjs to fetch the right cores from the CDN.
=> Add route in nginx for assets that 404s

frontend/src/views/Library/Scan/Base.vue
Should look similar to the following.
=> Adding overflow for scan log

docker/Dockerfile, docker/init_scripts/init
Instead of PUID/GUID, run the image as the `romm` user and use `user: "XXXX:XXXX"` in docker-compose/`docker run` to set the owner of newly created file/folders and mounted volumes.
=> Revert PUID/GUID and use `user` property in docker-compose

frontend/src/components/Details/ActionBar.vue, frontend/src/components/Gallery/AppBar/Base.vue, frontend/src/components/Gallery/AppBar/SelectingBtn.vue, frontend/src/components/Gallery/FabMenu/Base.vue, frontend/src/components/Game/Card/Cover.vue, frontend/src/stores/roms.ts
- Added a new button in the gallery app bar to enable a multi-select layer
- Now games can be selected without the need of ctrl/shift when at least one game is selected or multi-select layer is enabled
Closes #737
=> Improved multi-select games

backend/config/__init__.py, backend/handler/redis_handler.py, unraid_template/romm.xml
This PR adds more configuration for the external redis instance.
adds two new env vars:
`REDIS_USERNAME`: allows to specify username when using password (requirepass arg for redis creates "default" user)
`REDIS_DB`: helps separating databases when using single redis shared between multiple apps
=> Added more configuration for external redis

backend/handler/database/platforms_handler.py
If the entire folder gets removed from the filesystem, we should just purge the entire platform.
=> [ROMM-852] Purge platforms correctly on scan

frontend/index.html, frontend/src/components/AppBar/DrawerToggle.vue, frontend/src/components/Details/AdditionalContent.vue, frontend/src/components/Details/BackgroundHeader.vue, frontend/src/components/Game/Card/Cover.vue, frontend/src/components/LazyImage.vue, frontend/src/stores/platforms.ts, frontend/src/views/Gallery/Base.vue
* Switch `v-show` to `v-if` on gallery type
* Use simple `img` tag for gallery images
* Fix duplicate platforms in sidebar
* Preconnect to fonts endpoint
* Remove unnecessary `lazy-src`
=> Gallery view performance

docker/Dockerfile, docker/init_scripts/init
This change moves the virtualenv creation in the `Dockerfile` to a separate stage, to simplify isolating the process and reduce the need for uninstalling build dependencies.
The approach is similar to the one explained in [1]. It relies on building a virtualenv folder, and copying it in the final stage. Changing the `PATH` environment variable makes the virtualenv usable by default, without affecting the default Python installation.
Also, added Dockerfile arguments for Alpine, nginx, and Python versions, as some of them are reused, and also simplifies testing new versions.
An extra side effect is that the image size for the final stage is reduced from 315MB to 262MB.
[1] https://scribe.rip/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0
=> misc: Simplify backend environment configuration in Docker image

docker/Dockerfile
Avoid any changes in the `frontend/` folder to trigger `npm install`. Instead, split the copies to have separate steps for install and build.
=> fix: Improve Docker layer caching on frontend changes

.github/workflows/pytest.yml, .vscode/tasks.json, DEVELOPER_SETUP.md, backend/utils/generate_supported_platforms.py
Poetry 1.8.0 already includes support for `package-mode = false`, so there's no need to install a Poetry fork anymore.
=> misc: Remove mentions to unneeded Poetry fork

frontend/src/components/Gallery/AppBar/Base.vue, frontend/src/components/Gallery/FirmwareDrawer.vue
Now ``viewers`` can access the firmware menu to download
Fixes #955
=> Fixed firmware drawer permissions

backend/models/assets.py, backend/models/base.py, backend/models/firmware.py, backend/models/platform.py, backend/models/rom.py, backend/models/user.py, poetry.lock, pyproject.toml
This change applies the guided migration process recommended by SQLAlchemy [1], up to step 4, to have declarative ORM models that better support Python typing.
The change was tested by running `alembic check`, which does not find any schema changes.
Errors reported by `mypy` go down to 170, from the original 223 in the current `master` commit.
[1] https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#migrating-an-existing-mapping
=> misc: Migrate to SQLAlchemy declarative models

backend/handler/metadata/base_hander.py, backend/tasks/update_switch_titledb.py, backend/utils/iterators.py
This change should greatly reduce Redis calls, specially during application startup, as the JSON fixtures include thousands of keys that were being inserted one by one to Redis.
After upgrading to Python 3.12, we can remove the backport for `itertools.batched` introduced here.
=> fix: Call Redis HSET in bulk

backend/alembic/versions/0020_created_and_updated.py, backend/endpoints/responses/rom.py, backend/models/assets.py, backend/models/firmware.py, backend/models/platform.py, backend/models/rom.py, backend/models/user.py, backend/utils/iterators.py
Simplify annotations by using `__future__.annotations`, so there's no need to add typing using types as strings.
=> misc: Use Python future annotations

backend/endpoints/firmware.py, backend/endpoints/platform.py, backend/endpoints/rom.py, backend/endpoints/saves.py, backend/endpoints/screenshots.py, backend/endpoints/search.py, backend/endpoints/sockets/scan.py, backend/endpoints/states.py, backend/handler/database/firmware_handler.py, backend/handler/database/platforms_handler.py, backend/handler/database/roms_handler.py, backend/handler/tests/test_db_handler.py, backend/models/assets.py
The current implementation for some of the database handlers, where the same method is used to retrieve either a single entity (when an `id` is passed), a list of entities, or `None`, makes the typing and overall design more complex.
This change simplifies database handlers, by having two separate methods where appropiate:
* A method that receives an `id`, and returns either an entity, or `None`.
* A method that optionally receives filters, and returns (depending on the current handler implementation) a list of entities, or a `Select` object that allows chaining more SQLAlchemy operations.
=> misc: Split database handler logic to get/list entities

backend/handler/database/stats_handler.py
Instead of counting `Platform` rows, and filtering based on a subquery in `Rom`, we can simply count the different `platform_id` values in `Rom`.
=> misc: Simplify statistics query to retrieve platforms count

backend/endpoints/rom.py
Zip compression during multi-file ROM download is not needed. Commonly, ROMs are already compressed, and trying to compress them again on the fly does not reduce the generated file's size, while spending CPU power and making the download slower because of the compression process being the bottleneck.
By setting `level=0`, compression gets disabled, increasing download speed, and reducing CPU usage. CPU still gets a usage peak, because of Zip requiring a CRC32 calculation over each file's content.
* **Before** these changes:
* **After** these changes:
=> fix: Disable zip compression on ROM download

backend/alembic/versions/0023_make_columns_non_nullable.py, backend/models/collection.py, backend/models/platform.py, backend/models/rom.py, backend/models/user.py
This change makes some database columns non-nullable, and includes the migration to seamlessly upgrade the schema.
It includes:
* User and Platform names
* Every boolean column
=> fix: Make some DB columns non-nullable

backend/handler/metadata/sgdb_handler.py, env.template
The SteamGridDB API has a bug, where the `total` field for the paginated endpoint `/v2/grids/game/:gameId` sometimes double/triple counts results (e.g. returning `total=172` when there are actually 86 results).
To avoid this issue, this change relies on each page's number of results. If the received page has less than the requested amount of grids, we know that is the last page.
=> fix: Correctly traverse SteamGridDB API pages

backend/endpoints/collections.py, backend/endpoints/rom.py, backend/endpoints/user.py, examples/docker-compose.example.yml, frontend/src/components/Details/Saves.vue, frontend/src/components/Details/States.vue, frontend/src/components/Gallery/FabOverlay.vue, frontend/src/components/common/Game/Card/Base.vue, frontend/src/components/common/Game/Dialog/EditRom.vue, frontend/src/components/common/Game/Dialog/SearchRom.vue, frontend/src/components/common/Game/FavBtn.vue, frontend/src/components/common/Platform/Icon.vue, frontend/src/components/common/RDialog.vue, frontend/src/layouts/Management/Excluded.vue, frontend/src/layouts/Management/PlatformBinding.vue, frontend/src/layouts/Management/PlatformVersions.vue, frontend/src/stores/config.ts, frontend/src/views/Gallery/Collection.vue, frontend/src/views/Gallery/Platform.vue, frontend/src/views/Play/Base.vue
- Fixed custom artwork for games and collections
- Fixed platform icons not showing
- Improved saves/states selector on play view
- Check existing users on wizard setup
- Updated docker-compose example
=> Fixes from beta testing

backend/endpoints/sockets/scan.py
My NAS didn't mount correctly after a reboot, so when the nightly scan ran, it found no files in the filesystem, and purged all the games from my library. This PR prevents purging all games during a scan, but still allows for manual removal via the UI.
=> Prevent mass purging of games and platforms during scan

README.md, examples/config.example.yml
Some users had issues with the current ``config.example.yml`` because it's not working when keeping untouched.
Adding some empty placeholders fix it and webUI will manage it automatically. Advanced users can manage it manually as always.
Also removed README warning about upgrading from 2.x to 3.x
=> Fix config.example.yml

backend/endpoints/search.py, backend/handler/metadata/sgdb_handler.py, backend/main.py
This change avoids blocking requests when retrieving covers from SteamGridDB, which is the main bottleneck as the current implementation iterates over paginated results for multiple games.
Using an asynchronous client like `httpx` provides a good performance improvement, and reduces the latency when calling this endpoint. Also, the inclusion of FastAPI `lifespan` allows instantiating a single client on startup.
When testing with "Final Fantasy V Advance", the endpoint goes from ~9s to ~1.5s to retrieve all covers.
=> feat: Use async requests to retrieve SteamGridDB covers

backend/handler/filesystem/firmware_handler.py, backend/handler/filesystem/platforms_handler.py, backend/handler/filesystem/roms_handler.py, backend/utils/filesystem.py
`os.walk` is a generator that can iteratively navigate from the specified path, top-bottom. However, most of the calls to `os.walk` in the project cast the call to `list()`, which makes it traverse the path and recursively find all nested directories.
This is commonly not needed, as we end up just using a `[0]` index to only access the root path.
This change adds a few utils that simplifies listing files/directories, and by default does it non-recursively. Performance gains shouldn't be noticeable in systems with high-speed storage, but we can avoid the edge cases of users having too many nested directories, by avoiding unneeded I/O.
=> fix: Avoid recursive os.walk calls

backend/main.py
With the introduction of non-paginated responses for ROMs, JSON responses for big collection could easily be at >1MiB.
This change adds a FastAPI-provided middleware to enable GZip compression for responses greater than 1KiB.
=> misc: Enable GZip compression for backend responses

backend/handler/filesystem/resources_handler.py
Instead of explicitly looking for .png files, we glob for any file that matches the folder structure
=> Fix covers deleted when uploading extension other then PNG

backend/endpoints/sockets/scan.py
=> [ROMM-1003] Fix aborting mid-scan

backend/tasks/update_switch_titledb.py
The existing code was failing after changes on the upstream JSON file that included entries with `null` ID.
=> fix: Filter Switch titledb entries with empty id

backend/endpoints/tests/test_identity.py, backend/main.py
Avoid conflicting cookie names when RomM runs in the same host as other applications, by adding a `romm_` namespace to the session cookie.
=> fix: Use namespaced cookie for session

backend/endpoints/tests/test_identity.py, backend/handler/metadata/base_hander.py, backend/handler/metadata/igdb_handler.py, backend/handler/redis_handler.py, backend/models/firmware.py, backend/tasks/update_switch_titledb.py
Introduce an asynchronous Redis instance to be used in async functions. Also, this change migrates most of the sync cache usage to the new async cache.
=> misc: Add Redis async cache

backend/endpoints/rom.py, backend/endpoints/search.py, backend/endpoints/sockets/scan.py, backend/endpoints/tests/test_assets.py, backend/endpoints/tests/test_config.py, backend/endpoints/tests/test_heartbeat.py, backend/endpoints/tests/test_identity.py, backend/endpoints/tests/test_oauth.py, backend/endpoints/tests/test_platform.py, backend/endpoints/tests/test_raw.py, backend/endpoints/tests/test_rom.py, backend/handler/metadata/moby_handler.py, backend/handler/metadata/sgdb_handler.py, backend/handler/scan_handler.py, backend/handler/tests/test_fastapi.py, backend/main.py, backend/utils/context.py
Convert `MobyGamesHandler` methods to be asynchronous, and use an `httpx` async client, instead of `requests` sync client.
This change also introduces a `ContextVar` and the concept of a context shared between requests. The context is automatically instrumented for FastAPI requests, by using a middleware.
For processes that do not run from within requests, the `@initialize_context()` decorator must be used. For example, for tasks triggered from `rq` workers.
=> misc: Migrate MobyGamesHandler to async

backend/endpoints/collections.py, backend/endpoints/rom.py, backend/endpoints/sockets/scan.py, backend/handler/filesystem/resources_handler.py, backend/handler/filesystem/tests/test_fs.py, poetry.lock, pyproject.toml
For filesystem resource handler, `requests` calls have been replaced with `httpx`, and file I/O has been replaced with `anyio` utils.
The existing approach to save covers and screenshots, by calling `shutil.copyfileobj` with the raw response is no longer needed. `httpx` does not provide a file-like object when streaming [1], so there's no easy drop-in replacement.
However, the applied solution correctly builds the file iteratively, by consuming the response in chunks.
[1] https://github.com/encode/httpx/discussions/2296
=> misc: Migrate filesystem resource handler to async

DEVELOPER_SETUP.md, backend/endpoints/collections.py, backend/endpoints/responses/collection.py, backend/endpoints/responses/rom.py, backend/handler/database/collections_handler.py, backend/handler/database/roms_handler.py, backend/models/rom.py, frontend/src/components/common/Collection/Dialog/EditCollection.vue, frontend/src/services/api/collection.ts
@zurdi15 did 90% of the work here, so this PR is just a question of exposing the public option to the user, and filtering the list of collections for users.
=> Public collections

backend/endpoints/platform.py, backend/endpoints/rom.py, backend/endpoints/search.py, backend/endpoints/sockets/scan.py, backend/endpoints/tests/test_rom.py, backend/handler/filesystem/resources_handler.py, backend/handler/metadata/igdb_handler.py, backend/handler/scan_handler.py, backend/handler/tests/cassettes/test_fastapi/test_scan_platform.yaml, backend/handler/tests/cassettes/test_fastapi/test_scan_rom.yaml, backend/handler/tests/test_fastapi.py, backend/tasks/tasks.py, poetry.lock, pyproject.toml
Convert `IGDBBaseHandler` methods to be asynchronous, and use an `httpx` async client, instead of `requests` sync client.
This change also removes the direct dependency with `requests`, as the project no longer uses it, preferring `httpx` instead.
=> misc: Migrate IGDBBaseHandler to async

.trunk/configs/ruff.toml, backend/endpoints/collections.py, backend/endpoints/rom.py, backend/endpoints/user.py
`ASYNC` rules [1] try to find issues regarding asynchronous code. This change enables `ruff` to start reporting these issues, and fixes existing warnings.
[1] https://docs.astral.sh/ruff/rules/#flake8-async-async
=> fix: Enable flake8-async rules in ruff and fix warnings

backend/tasks/update_switch_titledb.py
Only for this scheduled task, the run was failing because there was no context initialization that created the httpx session.
Other schedules work as expected, because they do have context initialization in the functions they call to (e.g. `scan_platforms`).
=> fix: Initialize context on scheduled task

backend/handler/metadata/igdb_handler.py
This improvement avoids extra IGDB API requests when a received Rom is an exact match. It avoids up to 2 requests per Rom, when an exact match is found.
=> fix: Return early if IGDB finds an exact match

backend/config/__init__.py, backend/endpoints/user.py, backend/handler/metadata/igdb_handler.py, backend/handler/redis_handler.py, backend/main.py, poetry.lock, pyproject.toml
Pytest v8.2 introduced the `PYTEST_VERSION` environment variable [1], that can be used to check if code is running from within a pytest run.
This way, we can avoid checking the loaded `sys` modules.
[1] https://docs.pytest.org/en/stable/changelog.html#id57
=> misc: Use PYTEST_VERSION variable to detect Pytest runs

frontend/src/views/Play/Base.vue, frontend/src/views/Play/Player.vue
When starting a game with a selected core or BIOS, re-use that same core or BIOS for future plays. Same goes for individual save files, but specific to the game played.
Fixes #1029
=> [ROMM-1029] Store and re-use last saved biois/save/state/core

frontend/src/components/Details/RelatedGames.vue, frontend/src/components/common/Game/Card/Related.vue
This PR fixes rendering related games when switching between games with search, and opens the IGDB page when clicking on a card.
=> Hotfix and link from related games

frontend/src/components/Gallery/FabOverlay.vue, frontend/src/services/api/rom.ts
We need to add a short delay when making multiple download requests to stop the browser from preventing the downloads.
Fixes #1012
=> [ROMM-1012] Fix multi-file download in gakllery view

backend/endpoints/auth.py, backend/endpoints/collections.py, backend/endpoints/config.py, backend/endpoints/feeds.py, backend/endpoints/firmware.py, backend/endpoints/heartbeat.py, backend/endpoints/platform.py, backend/endpoints/raw.py, backend/endpoints/rom.py, backend/endpoints/saves.py, backend/endpoints/screenshots.py, backend/endpoints/search.py, backend/endpoints/states.py, backend/endpoints/stats.py, backend/endpoints/tasks.py, backend/endpoints/user.py, backend/handler/auth/tests/test_oauth.py, backend/utils/router.py, backend/utils/test_router.py
According to multiple FastAPI discussions [1], FastAPI only includes a built-in mechanism to redirect requests including a trailing slash, to its variation without slash, using a `307` status code.
This can be an issue when certain clients do not send the same headers on the redirected request.
This change adds a custom FastAPI `APIRouter`, that registers both route path variations (with and without trailing slash), while only marking the path without slash for being included in the OpenAPI schema.
[1] https://github.com/fastapi/fastapi/discussions/7298
=> misc: Make backend handle URLs with trailing slash

backend/config/__init__.py, backend/endpoints/feeds.py, backend/endpoints/responses/feeds.py, backend/utils/router.py, env.template
* Add typing for nested objects in Tinfoil and Webrcade feed schemas.
* Do not send Rom background and thumbnail, if not available.
* Correctly build URLs using `starlette` utils.
* Deprecate the `ROMM_HOST` setting, no longer needed.
* Fix FastAPI custom router to prefer routes without trailing slash.
* Fix Webrcade background URL pointing to gallery screenshot.
=> misc: Improve typing for feed schemas

backend/endpoints/feeds.py
This matches the behavior of the Webrcade feed.
=> fix: Allow access to Tinfoil feed when download auth is disabled

docker/init_scripts/init
Currently, the `request.url_for` and `URLPath.make_absolute_url` methods always build URLs with "http" scheme, even when the original requested URL is using "https".
The reason for this is that Gunicorn does not allow IPs other than 127.0.0.1 to set secure headers by default. As regular RomM installations don't know which frontend IPs will try to set security headers in advance, we can disable this validation, and fix URL building.
A simple way to test this change is to access any of the `feed` endpoints, which generate URLs using the mentioned methods. Accessing the endpoint using "https" scheme must generate "https" URLs.
Reference:
* https://github.com/encode/starlette/issues/538#issuecomment-2054013679
* https://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips
=> fix: Set Gunicorn option forwarded-allow-ips

frontend/package-lock.json, frontend/package.json, frontend/src/views/EmulatorJS/Player.vue
Emulation is currently broken since they purged 4.0.12 from the releases (and cores in the CDN), so we need to bump this up ASAP.
=> Bump emulatorjs to 4.1.1

.trunk/trunk.yaml, backend/endpoints/responses/rom.py, backend/endpoints/rom.py, backend/handler/filesystem/firmware_handler.py, backend/handler/filesystem/roms_handler.py, backend/utils/hashing.py, backend/utils/nginx.py, docker/Dockerfile, docker/nginx/default.conf, docker/nginx/js/decode.js, frontend/src/services/api/rom.ts, poetry.lock, pyproject.toml
This change installs and configures the `mod_zip` nginx module [1], which allows nginx to stream ZIP files directly.
It includes a workaround needed to correctly calculate CRC-32 values for included files, by including a new `server` section listening at port 8081, only used for the file requests to be upstream subrequests that correctly trigger the CRC-32 calculation logic.
Also, to be able to provide a `m3u` file generated on the fly, we add a `/decode` endpoint fully implemented in nginx using NJS, which receives a `value` URL param, and decodes it using base64. The decoded value is returned as the response.
That way, the contents of the `m3u` file is base64-encoded, and set as part of the response, for `mod_zip` to include it in the ZIP file.
[1] https://github.com/evanmiller/mod_zip
=> feat: Use nginx mod_zip to generate multi-file zip downloads

backend/config/config_manager.py, backend/decorators/database.py, backend/handler/database/base_handler.py
As recommended by SQLAlchemy [1], this change makes a single instantiation of the database engine and session maker, instead of one entity per handler.
It also uses the provided `URL` constructor to better define the database URL structure.
[1] https://docs.sqlalchemy.org/en/20/core/connections.html#basic-usage
=> misc: Use single SQLAlchemy engine and session maker

backend/endpoints/rom.py, backend/utils/filesystem.py, frontend/src/components/common/Game/Dialog/EditRom.vue
Some filesystems and OSs can't handle certain characters, so we remove-or-replace them when a) manually editing the filename or b) setting the filename to IGDB/Moby field value.
Fixes #392
=> Replace illegal fs chars in filenames

.gitignore, backend/endpoints/rom.py, frontend/src/components/common/Game/Dialog/UploadRom.vue, frontend/src/components/common/UploadInProgress.vue, frontend/src/services/api/rom.ts, frontend/src/stores/upload.ts
Keeps the snackbar open if there are failed uploads, and displays the failure reason. Users can clear the uploads using the new "Clear finished" button at the bottom.
=> Upload dialog hotfixed + clear button

backend/endpoints/feeds.py, backend/endpoints/responses/feeds.py
If the game already has a productID in the file name, try to match it against the internal XML list. If a match is found, add an entry in the `titledb` field, as per the [the tinfoil docs](https://blawar.github.io/tinfoil/custom_index/#adding-metadata).
=> Add titledb field to tinfoil response

backend/handler/database/platforms_handler.py, frontend/src/stores/roms.ts
This PR removes the selectin load for platforms, which is no longer needed since we now calculate rom count using a `column_property`. It also switches to using `Set` when managing the filtered lists of games, which is way faster then nested array filters.
=> Better performance for large collections

backend/config/__init__.py, backend/endpoints/rom.py, env.template, frontend/vite.config.js
New `DEV_MODE` env variable explicitly set in `.env` and defaults to false. Since emujs only needs HEAD requests to fetch content location, then direct downloads to browser, change is only needed in `head_rom_content`.
=> Hack to get emujs working in dev mode

backend/handler/filesystem/roms_handler.py, poetry.lock, pyproject.toml
Recent versions of Microsoft Windows Explorer use Deflate64 compression when creating ZIP files larger than 2GB. These files are not well supported in open-source zip libraries due to it's closed-source nature, so we patch `zipfile` to support them.
Fixes #1155
=> [ROMM-1155] Patch zipfil + catch more 7zip errors

backend/handler/database/roms_handler.py
`get_sibling_roms` no longer exists, and we need to explicitly fetch the rom from the db (otherwise the connection closes early)
=> [ROMM-1154] Fix setting main sibling

frontend/src/components/common/Collection/Dialog/CreateCollection.vue, frontend/src/components/common/Collection/Dialog/EditCollection.vue, frontend/src/components/common/Game/Dialog/EditRom.vue
* Initialize `removeCover` as `false` on each dialog render, so previous overrides don't affect the initial state.
* Make both file upload and cover online search update `removeCover` to false.
* Fix collection update to send `remove_cover` to the API.
Potential fix for #1169.
=> fix: Correctly update state for cover deletion

frontend/src/components/common/Game/Dialog/MatchRom.vue
If a game is manually unmatched, we update its `name` field to `file_name` (which includes both tags and extension). After that, if we go to the Rom list, and click on "Manual match" for that rom, the search field is populated with that Rom name, which commonly won't retrieve any results from the metadata providers.
This change makes the "Manual match" search term to use the filename without tags or extension, when the Rom is currently not matched. It also triggers the search automatically when a search term was set.
Potential fix for #1167.
=> fix: Use filename without tags or extension when matching unmatched game

backend/endpoints/responses/rom.py, backend/endpoints/sockets/scan.py, docker/nginx/default.conf, frontend/src/services/api/rom.ts
The core changes are in the nginx config, where we increase the timeout for any calls to the api to 600 seconds (10 minutes), and tell nginx not to buffer requests. This should allow for direct upload streaming, which I've confirmed by testing on my server.
=> Bypass nginx proxy buffering when uploading roms

docker-compose.yml, docker/Dockerfile, docker/init_scripts/init
This change replaces the bundled Redis server with Valkey. No breaking changes are introduced, as considered environment variables still maintain the `REDIS_` prefix.
Fixes #925.
=> misc: Use bundled Valkey instead of Redis server

backend/adapters/services/rahasher.py, docker/Dockerfile
Build and include the `RAHasher` binary in the Docker image, to calculate hashes for RetroAchievements. Also, add a service to run `RAHasher` from Python.
Example usage:
```python
from adapters.services.rahasher import RAHasherError, RAHasherService
rahasher = RAHasherService()
try:
hash = await rahasher.calculate_hash("nes", Path("path/to/rom.nes"))
except RAHasherError:
hash = None
```
=> feat: Add RAHasher and util to calculate RetroAchievements hashes

backend/endpoints/rom.py, backend/utils/filesystem.py, backend/utils/nginx.py
When serving files using the `X-Accel-Redirect` header in nginx, the header values must be URL-encoded. Otherwise, nginx will not be able to serve the files if they contain special characters.
This commit adds a new `FileRedirectResponse` class to the `utils.nginx` module, to simplify the creation of responses that serve files using the `X-Accel-Redirect` header.
Fixes #1212, #1223.
=> fix: Escape URLs when files are served by nginx

backend/handler/filesystem/roms_handler.py, poetry.lock, pyproject.toml
This change improves memory usage, by only keeping a single archive's member file in memory at a time during 7zip decompression.
The `py7zr` library does not support streaming decompression yet, so this change is the best we can do for now.
Potential fix for #1211, but it won't improve memory usage for single-file 7zip archives.
=> fix: Improve memory usage during 7zip decompression

frontend/src/views/RuffleRS/Base.vue
According to Ruffle documentation [1], the `preferredRenderer` option is only needed if a renderer needs to be enforced. When not provided:
> By default, Ruffle chooses the most featureful backend supported by the user's system, falling back to more basic backends if necessary.
This commit removes the `preferredRenderer` option from the Ruffle configuration in the frontend, so that the default behavior is used.
It also removes the noisy `logLevel` option, which was set to `debug`.
Fixes rendering issue for `Boxhead: The Rooms`, reported in #1216.
[1] https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle
=> fix: Do not set Ruffle's renderer explicitly

backend/watcher.py
The `scan.py` module was moved to the `sockets` package, but this line was not updated to reflect that change. This currently causes the watcher to not skip queuing a new `scan_platforms` task if one is already scheduled.
=> fix: Skip scanning task by checking against the correct function name

backend/endpoints/collections.py, backend/endpoints/rom.py, backend/handler/filesystem/resources_handler.py
The previous implementation was calling `resize_cover_to_small` within the context manager that was writing the image to the filesystem. This was causing `PIL` to raise an error because it could not identify the open and temporarily created file as a valid image.
Instead of saving the original image to the filesystem and then resizing it, we now open the image in memory, resize it, and then save it to the filesystem. We also avoid reading the `BytesIO` object twice by saving small and big images from the same initial `Image` object.
Fixes #1191.
=> fix: Correctly resize and save small artwork

frontend/src/components/common/Platform/Icon.vue
When a platform slug is not present in `PLATFORMS_VERSIONS`, which is the common case overall, the component was trying to fetch an `undefined.ico` image.
Instead of that, we should check if the platform slug is present in `PLATFORMS_VERSIONS` and if not, fallback to the platform slug itself.
=> fix: Avoid image requests for undefined.ico platform icon

backend/endpoints/rom.py, backend/handler/database/roms_handler.py
Related to #1123
I'm modifying local ROM management software (such as ES-DE) to query a RomM server for ROMs, as well as to download them for use on the local machine's emulators. Huge database sizes came to be an issue as there would be a timeout when attempting to make a query to the database, but would also create a better user experience of having some list of ROMs available immediately rather than waiting for the query for the entire set of requested ROMs to be completed.
The frontend making use of this is not a part of this pull request, but I would assume this can be used for pagination as mentioned in the referenced issue.
=> Add offset parameter to get_roms endpoint

backend/endpoints/tests/test_identity.py, backend/endpoints/user.py
The `add_user` endpoint was querying the database at import time, to decide whether to enforce the `users.write` scope or not. This is problematic because the database might not be ready at import time.
Also, the decided `scopes` was being maintained for the entire application lifetime, which is not ideal, as users can be created without having the `users.write` scope, until the application is restarted.
=> fix: Avoid query during import time to set add_user endpoint scopes

backend/endpoints/tests/test_identity.py, backend/endpoints/user.py, backend/handler/database/users_handler.py
Instead of fetching all users and checking if the new username is present in the list, we can directly query the database for the username.
=> fix: Simplify query that validates new username already exists

backend/decorators/auth.py, backend/endpoints/collections.py, backend/endpoints/config.py, backend/endpoints/feeds.py, backend/endpoints/firmware.py, backend/endpoints/platform.py, backend/endpoints/raw.py, backend/endpoints/rom.py, backend/endpoints/saves.py, backend/endpoints/screenshots.py, backend/endpoints/search.py, backend/endpoints/states.py, backend/endpoints/tasks.py, backend/endpoints/user.py, backend/handler/auth/base_handler.py, backend/models/user.py
Instead of using just strings, this change converts the scopes to a `StrEnum`, to be compatible with places where a string is expected. This avoids typos when using these scopes, simplifies searching for usages, and improves type hints.
An extra change was the fix to the Firmware download endpoint, which wasn't respecting the `DISABLE_DOWNLOAD_ENDPOINT_AUTH` flag.
=> misc: Create enum for authorization scopes

backend/handler/filesystem/roms_handler.py
The `tar` decompression function was failing for some users, with error message:
```
'NoneType' object does not support the context manager protocol
```
As explained in the official documentation [1], the `extractfile` method returns `None` if the member is not a regular file or a link. This change skips any member that is not a regular file.
[1] https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractfile
=> fix: Make tar decompression only consider regular files

backend/handler/metadata/igdb_handler.py
Some of the image links for IGDB age ratings were broken. This commit fixes all of them.
=> fix: Broken IGDB age rating image links

backend/handler/metadata/igdb_handler.py
The IGDB API provides screenshots in 720p resolution, when either `screenshot_huge` or `720p` size values are used [1]. The `screenshot_huge` uses `Lfill`, while `720p` uses `Fit` as the resizing method.
That means that either `screenshot_huge` or `720p` will provide the correct aspect ratio for 16:9 platforms. However, for platforms with a different aspect ratio, we need to use the `720p` size value to get the correct image instead of a cropped one.
Example:
- [`screenshot_huge`](https://images.igdb.com/igdb/image/upload/t_screenshot_huge/c77bodnkwu73gs2jwhw4.jpg)
- [`720p`](https://images.igdb.com/igdb/image/upload/t_720p/c77bodnkwu73gs2jwhw4.jpg)
[1] https://api-docs.igdb.com/#images
=> fix: Download IGDB screenshots with right aspect ratio

frontend/src/components/common/Game/Dialog/MatchRom.vue
The source image was not being shown on the results of the manual match dialog, because scrapper image names do not match the source names. To avoid this issue, the `MatchedSource` type was updated to include a `logo_path` property, which will be used to set the correct image path.
Before:
After:
=> fix: Show source image on each result for Manual match

.trunk/trunk.yaml, backend/adapters/services/igdb_types.py, backend/handler/metadata/igdb_handler.py, poetry.lock, pyproject.toml
The short-term goal is to completely typehint the IGDB API responses. This first change adds the base structures and enums RomM currently uses.
The `ExpandableField` type will allow us to model the expansion mechanism the IGDB API provides, where a field can include either an ID, or the full nested structure.
=> misc: Initial addition of IGDB typehints

docker/Dockerfile
Use `tini` [1] as the container entrypoint to ensure that the container process is properly reaped when the container is stopped.
This is needed as the main container command is a shell script.
A simple way to test this change is to:
1. Build the container image and run it using `docker compose up`.
2. Within the same terminal, stop the container using `Ctrl+C`.
3. Verify that the container is properly stopped right away.
Without `tini`, the container takes a few seconds to stop, and it makes one CPU core to be used at 100% during that time.
[1] https://github.com/krallin/tini
=> misc: Use tini as container entrypoint

frontend/src/components/Details/Personal.vue, frontend/src/utils/index.ts
Fixed personal tab in the game details view on mobile
=> fix: Personal tab mobile responsive

backend/endpoints/rom.py
This reverts commit e2bfbacfbc5d4035f6f95ba2b6d76815b587c811. The fix has been applied to the `master` branch in PR #1224.
=> Revert "Update rom.py to Fix Filename error"

frontend/src/stores/roms.ts
Makes the read from localStorage consistent with reads of the other settings elsewhere in the codebase.
Would probably be nice to have grouping happen in the "recents" view too, but that would take more substantial changes and a deeper understanding of the codebase by me.  :)   If I get more time, maybe I will submit a separate PR for that.
=> Fix #1283 - properly default groupRoms if it doesn't exist in localStorage

backend/handler/filesystem/roms_handler.py, backend/utils/archive_7zip.py, docker/Dockerfile, poetry.lock, pyproject.toml
At the moment, 7zip files are generating memory issues and even OOM errors on user installations. This is because the current stable release of `py7zr` does not support decompression streaming, and RomM needs to decompress the each 7zip file in the library into memory to be able to calculate hashes.
This change introduces a `py7zr` fork I created to have a stable commit SHA to refer to in case upstream gets any forced pushes. It includes the contents of the pull request the `py7zr` creator is working on to support decompression streaming [1].
The way decompression streaming is implemented in `py7zr` is different than the other compression utilities. Instead of being able to provide a `bytes` iterator, we need to provide a `Py7zIO` implementation that will call a callback on each read and …
=> feat: Add streaming support for 7zip hashing

examples/docker-compose.example.yml
This commit adds a healthcheck configuration to the MariaDB service in the Docker Compose example configuration. The healthcheck script is a simple shell script that checks if the MariaDB server is ready to accept connections.
The application will wait for the MariaDB service to be healthy before starting the application service. This should solve issues where the database takes longer to start than the application, and logs some `Something went horribly wrong with our database` errors.
This change also stops recommending the `linuxserver/mariadb` image as an alternative. We have had users that change the image because of the first time run triggering those errors, but the `linuxserver/mariadb` image requires a different configuration that could be confusing for new users (e.g. volume …
=> misc: Add MariaDB healthcheck recommendation to Docker Compose config

backend/handler/metadata/igdb_handler.py
IGDB provides alternative names for games, which we are currently not considering when checking for an exact match.
This change starts considering alternative names, in addition to the game's name and slug, when checking for an exact match.
=> fix: Consider IGDB alternative names when checking for exact match

backend/handler/metadata/igdb_handler.py
This change includes more categories when matching IGDB games. While testing, some games were incorrectly matched to the wrong game, and the reason was that the game was a Port (e.g. `Arkanoid`, `Contra`, `Double Dragon`, `Metal Gear` for NES), a Remake (e.g. `Adventure Island` for NES), or a Remaster.
=> fix: Consider more categories when matching IGDB games

backend/main.py
=> [ROMM-1218] Exempt the right path from CSRF protection for tokens

backend/endpoints/sockets/scan.py
When the scanning process fiends that a rom should not be scanned, it was still updating the rom data in the database.
This database update is only needed when the existing data is different to the newly found filesystem data, so we can avoid most of the updates for already existing library roms.
=> fix: Speed up scan for matched roms without filesystem changes

DEVELOPER_SETUP.md, backend/handler/auth/base_handler.py, backend/handler/auth/middleware.py, docker-compose.yml, frontend/src/components/common/Navigation/SettingsDrawer.vue, frontend/tsconfig.json
When setting up a new installation, if the browser has old cookies (romm_session cookie specifically) from an old instance or from an user that no longer exists in the database, RomM crashes without recover. This fix adds a check in the middleware to avoid the crash and clean the session cookies gracefully.
Closes #1266
=> fix: Crash on new instance from previous installation

docker/Dockerfile, docker/init_scripts/docker-entrypoint.sh
This change allows setting environment variables with a `_FILE` suffix, which will be used to load the contents of the file specified in the variable into the variable without the suffix.
For example, setting `ROMM_AUTH_SECRET_KEY_FILE=/run/secrets/romm_auth_secret_key` and creating a file with the secret key at the specified path will set `ROMM_AUTH_SECRET_KEY` to the contents of the file.
A common use case for this is to use secrets in Docker Compose [1], to avoid exposing secrets in the `docker-compose.yml` or `env` files.
[1] https://docs.docker.com/compose/how-tos/use-secrets/
=> feat: Add support for _FILE suffix in environment variables

backend/models/platform.py, backend/models/rom.py
* `Platform.aspect_ratio` needs a string length, otherwise we get `sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mariadb`
* Add two indexes that are created in `0024_sibling_roms_db_view.py` but never added to the models
=> Hotfixes for some sqlalchemy models

backend/endpoints/user.py
The previous version didn't allow users to update their own password. This keeps the endpoint to authed users only, and the check on L141 actually checks for perms to update the user.
=> [HOTFIX] Lower permission on update user endpoint and check perms internally

backend/handler/filesystem/roms_handler.py
The `get_roms` method is used during scanning and to generate feeds. Sorting by filename is not perfect (e.g. prefixes like "The" or "A"), but should be good enough for users to better visualize how the scanning process is going, and how close it's to finish.
=> misc: Sort roms in get_roms method

frontend/src/utils/index.ts
Fixes #1219. Typo found by @Subtixx in that same issue.
=> fix: Typo in parallel_n64 core name

docker/Dockerfile, docker/init_scripts/init
`tini` (added in [PR](https://github.com/rommapp/romm/pull/1272)) does not wait for child processes to exit gracefully, so all processes will be killed immediately. This is why the container stops so fast.
Possible `tini` issue: https://github.com/krallin/tini/issues/180
This fix makes the `init` script listen and handle terminate signals. It also ensures that child processes are shut down in reverse order with proper waiting for completion.
To see exit codes of processes I used  `exitsnoop-bpfcc` tool from this [toolset](https://github.com/iovisor/bcc). Not sure maybe it is possible in easier way.
This command started in terminal: `sudo exitsnoop-bpfcc | egrep '(gunicorn|valkey|nginx|python3)'`
```
romm  | INFO:     [RomM][watcher][2024-12-26 02:04:50] Watching /romm/library for changes …
```
=> fix: Handle terminate signals in init script

frontend/src/views/Auth/Login.vue
The "or" divider was being displayed in the login form even when OIDC was disabled.
=> fix: Hide "or" divider in Login form when OIDC is disabled

docker/Dockerfile
This commit improves Docker layer caching by installing the required packages in the `production-stage` stage, before copying files from other stages.
This way, dependency installation will remain cached unless there's a change in the required `apk` packages (or the stage's base image).
=> misc: Improve Docker layer caching by installing dependencies before copying

backend/config/__init__.py, backend/main.py, backend/scheduler.py, backend/utils/__init__.py, backend/watcher.py, backend/worker.py, poetry.lock, pyproject.toml
This change initializes the Sentry SDK, which enables error tracking when the `SENTRY_DSN` environment variable is set.
Drop-in alternatives to Sentry are also supported, like GlitchTip.
=> feat: Initial Sentry support

backend/endpoints/auth.py, backend/handler/auth/base_handler.py, backend/handler/auth/tests/test_oidc.py
This patch removes quite a bit of code that is unnecessary because the relevant checks are already done in authlib (specifically in https://github.com/lepture/authlib/blob/master/authlib/integrations/base_client/sync_openid.py - the parse_id_token is called when we invoke oauth.openid.authorize_access_token). Therefore it is not necessary for us to do this check again.
This also fixes an issue where the IdP jwks_url returns more than one valid key and it is necessary to use the kid to get the correct key (see line 72 of the aforementioned source).
I also verify that email_verified is set True for security reasons.
=> OIDC fix auk

frontend/src/utils/index.ts, frontend/src/views/Player/EmulatorJS/Player.vue
EmulatorJS version `4.2.0` supports PPSSPP core for PSP emulation.
This change enables PSP emulation in experimental mode. It requires the browser to support `SharedArrayBuffer` for multi-threading support.
Currently, RomM is not Cross-Origin Isolated, which is required for browsers to enable `SharedArrayBuffer`. In the meantime, Chrome can be executed using the following command, to enable `SharedArrayBuffer`:
```shell
chrome --enable-features=SharedArrayBuffer
```
=> feat: Experimental PSP emulation

backend/endpoints/search.py
Fixes PostgreSQL query error reported in:
https://github.com/rommapp/romm/issues/667#issuecomment-2571428721
=> fix: Change rom_id type to int in search endpoint

backend/endpoints/search.py, backend/handler/metadata/igdb_handler.py, backend/handler/metadata/moby_handler.py
The previous function name `get_matched_roms_by_id` was misleading as it returned a list of matched ROMs, but searching by ID should always return either one result or none.
=> misc: Change signature for get_matched_rom_by_id function

docker/Dockerfile
This change removes the installation of `dev` and `test` Poetry dependency groups from the published Docker images.
Developers are still able to use images with development dependencies installed, by either using the `dev-slim` or `dev-full` targets.
Image size comparison:
* `slim-image`: Down from 455 MiB to 355 MiB.
* `full-image`: Down from 760 MiB to 660 MiB.
=> feat: Stop installing development dependencies in Docker images

.github/workflows/typecheck.yml, frontend/package-lock.json
There is a npm bug that sometimes omits those fields. For reproducibility this is needed. I added a CI check in the second commit that will fail if there are missing fields.
The versions are not changed (the lockfile was not regenerated), just fixed with  https://github.com/jeslie0/npm-lockfile-fix
=> Fix lockfile to add integrity

frontend/src/components/Details/ActionBar.vue, frontend/src/components/common/Game/Card/ActionBar.vue, frontend/src/components/common/Game/Dialog/ShowQRCode.vue, frontend/src/utils/index.ts
A bit of refactoring so it also checks for `.3ds` files and marks the game as "qrcode-able".
=> [ROMM-1431] Allow downloading .3DS files with QR code

.github/workflows/typecheck.yml
I messed up the escaping of strings in #1434
=> ci: fix escaping of strings in jq command

backend/decorators/auth.py
Use `authlib` util `get_well_known_url` to get the well-known URL for the OIDC server metadata. This will ensure that the URL is correctly formatted and does not fail when the OIDC server application URL has a trailing slash.
Fixes #1430.
=> fix: Do not fail when OIDC server application URL has a trailing slash

backend/handler/database/collections_handler.py, backend/handler/database/roms_handler.py, backend/models/rom.py, backend/utils/database.py
Fix `json_array_contains_value` function to use the `@>` operator for checking if a JSON array contains a value in PostgreSQL. This is necessary because the `has_key` function only works for string values.
Also, remove `get_rom_collections` method, as it was doing the same thing as `get_collections_by_rom_id`.
Fixes #1441.
=> fix: Use proper JSON contains function for PostgreSQL

backend/handler/auth/base_handler.py, backend/handler/auth/tests/test_oidc.py
The OIDC email verified check now fails if the email is explicitly unverified, or if the `email_verified` claim is supported and the email is not explicitly verified.
Previously, the OIDC implementation failed for any OIDC provider that did not include the `email_verified` claim in the userinfo response. Providers like Synology do not include this claim, so the check always failed with error "Email is not verified."
I haven't found a formal specification for the `email_verified` claim, and how it should be handled, but this implementation should be more robust and work with more OIDC providers.
Fixes #1446.
=> fix: Improve OIDC email verified check

backend/config/__init__.py, backend/decorators/auth.py
Can't default the value to `/etc/ssl/certs/ca-certificates.crt` since it'll cause oauth to try and fetch it, which we don't want when not using encryption. 
Fixed #1442
=> [ROMM-1442] Add OIDC_TLS_CACERTFILE path to mounted certfile

frontend/src/utils/index.ts
Only a simple check since webGL is fairly well supported across all major engines.
=> [ROMM-1335] Check for webGL when testing emulatorjs supported

docker/Dockerfile, poetry.lock, pyproject.toml
Stop using `py7zr` fork and move to `1.0.0rc2` release, which includes decompression streaming support.
=> misc: Move to py7zr v1.0.0rc2

backend/handler/socket_handler.py, backend/utils/json.py
Similar to how `engineio` provides a JSON-compatible module, this change adds a custom JSON encoder with support for additional types.
Changing SocketIO's JSON module fixes the encoding issue when the scanning process tried to send a datetime, failing and the frontend not displaying the scanned game (commonly, when it had sibling games)
=> fix: SocketIO JSON dumps with sane defaults

frontend/src/utils/index.ts
https://emulatorjs.org/docs/systems/playstation#cores
Fixed #1297
=> [ROMM-1297] Fix loading psx mednafen core

docker/Dockerfile, poetry.lock, pyproject.toml
This change avoids a hard dependency on Poetry to define extra dependencies, like `dev` and `test` groups.
=> misc: Migrate optional dependencies to standard pyproject format

.github/workflows/pytest.yml, DEVELOPER_SETUP.md, pyproject.toml
With Poetry 2.0, we now need to explicitly tell it to install the `test` extra.
=> fix: Poetry dependency installation during pytest job

backend/alembic/versions/0030_user_email_null.py, backend/endpoints/user.py
When a user does not set an email address, we now set it to `NULL` in the database. That bypasses the unique constraint on the `email` column, allowing multiple users to have no email address set.
Fixes #1445.
=> fix: Set users email to null if empty

backend/endpoints/rom.py, frontend/src/utils/index.ts, frontend/src/views/Player/EmulatorJS/Player.vue
The way EmulatorJS checks for control schemes is based on the core, but since we pass in `EJS_core` values that are used by multiple platforms, it matches against the wrong platform when trying to build the controller button list. This PR bypasses the issue for the problem systems (those using `genesis_plus_gx` or `picodrive` cores).
Also re-enabled sega32X now that it's working again, and returns a `FileResponse` in dev mode to get emujs working again locally.
Fixes #1484
=> [ROMM-1484] Manually set control scheme for sega games

backend/config/__init__.py
The `logging.setLevel` method expects the log level to be in uppercase. This change ensures that the `LOGLEVEL` config value is always in uppercase.
=> misc: Do not fail if LOGLEVEL is not uppercase

backend/endpoints/rom.py, backend/handler/auth/middleware.py
Also fixes igdb_id and moby_id getting unset when not provided to `update` endpoint.
Fixes #1505
=> [ROMM-1505] Skip CSRF checks when request has Authorization header

frontend/src/stores/roms.ts
Small UI change.
The Recently Added element displays every sibling whereas the Platform pages do not, this streamlines that by making the roms under Recently Added behave similarly, it will only display the main sibling (or the first entry) per metadata id. Continue Playing will still show the individual siblings.
A cleaner solution would obviously be a dropdown in the UI to select the specific version (perhaps more so for Continue Playing) but I don't feel like going that far right now. Feel free to decline if this is intended behavior though.
Before:
The displayed ids in order: `17, 16, 15, 13, 12, 10, 9`
After:
The displayed ids in order: `17, 16, 15, 13`
=> fix: Remove sibling roms from Recently Added.

backend/utils/database.py
Loving the project so far 😎! Thanks for adding MySQL support!
I am running into an issue using MySQL. When viewing a ROM, it yields the error:
```
(mysql.connector.errors.DataError) 3146 (22032): Invalid data type for JSON data in argument 1 to function json_contains; a JSON string or JSON type is required.
```
This is beacuse for mySQL, the driver expects a string here, and receives an int. This PR fixes it by calling json.dumps(value) before passing the value to json_contains. This doesn’t affect Postgres, which uses different logic (has_key/contains).
I have tested and verified this running Romm 3.7.2 with mySQL ~8.0~ 9.1.0 on Unraid 🚀
=> Fix MySQL json_contains Error by Converting Non-String Values to JSON Strings

frontend/src/components/Gallery/FabOverlay.vue
The backend fails when a platform is sent as a string, and it's using PostgreSQL as the database engine. This change fixes the frontend to correctly send the platform_id as an integer value.
=> fix: Send platform as int in scan message

backend/alembic/versions/0031_datetime_to_timestamp.py, backend/alembic/versions/0032_longer_fs_fields.py, backend/alembic/versions/0033_rom_file_and_hashes.py
* Remove MySQL specific dialect.
* Fix migration `0033` to run on PostgreSQL.
* Correctly concatenate file paths by inserting a slash between path and file name.
=> fix: Adapt new migrations to supported database engines

backend/endpoints/auth.py, backend/endpoints/collections.py, backend/endpoints/configs.py, backend/endpoints/feeds.py, backend/endpoints/firmware.py, backend/endpoints/heartbeat.py, backend/endpoints/platform.py, backend/endpoints/raw.py, backend/endpoints/rom.py, backend/endpoints/saves.py, backend/endpoints/screenshots.py, backend/endpoints/search.py, backend/endpoints/states.py, backend/endpoints/stats.py, backend/endpoints/tasks.py, backend/endpoints/user.py
Improve OpenAPI documentation by setting tags to each API router. Also, set a prefix to each router to group the endpoints by their functionality.
=> misc: Set prefix and tags to API routers

backend/endpoints/collections.py, backend/endpoints/configs.py, backend/endpoints/firmware.py, backend/endpoints/platform.py, backend/endpoints/rom.py, backend/endpoints/saves.py, backend/endpoints/screenshots.py, backend/endpoints/states.py, backend/endpoints/stats.py, backend/endpoints/user.py
The addition of prefixes in API routes broke any forward-slash-only endpoint `"/"`, so this PR removed all them them. The changes in `APIRouter` should cover an weird edge cases.
=> [HOTFIX] Remove single forward-slash endpoints

backend/endpoints/sockets/scan.py, frontend/src/components/common/Game/Dialog/UploadRom.vue, frontend/src/components/common/Navigation/SettingsDrawer.vue, frontend/src/layouts/Main.vue, frontend/src/stores/auth.ts, frontend/src/stores/collections.ts, frontend/src/stores/config.ts, frontend/src/stores/download.ts, frontend/src/stores/galleryFilter.ts, frontend/src/stores/galleryView.ts, frontend/src/stores/heartbeat.ts, frontend/src/stores/language.ts, frontend/src/stores/navigation.ts, frontend/src/stores/notifications.ts, frontend/src/stores/platforms.ts, frontend/src/stores/roms.ts, frontend/src/stores/runningTasks.ts, frontend/src/stores/scanning.ts, frontend/src/stores/upload.ts, frontend/src/stores/users.ts, frontend/src/views/GameDetails.vue
* Unity clearing pinia caches under `reset` command and run on logout
* Run hash calculations in the same background process
* Rational: it's ok if scans take longer since they calculate hashes, and better to have them available on scan when we start integrating hasheous
=> Reset stores on logout + move hash calc out of background on scan

.trunk/trunk.yaml, frontend/src/components/common/Collection/Card.vue, frontend/src/components/common/Collection/ListItem.vue, frontend/src/components/common/Collection/RAvatar.vue, frontend/src/components/common/Game/Card/Base.vue, frontend/src/components/common/Game/ListItem.vue, frontend/src/components/common/Game/Table.vue, frontend/src/stores/collections.ts, frontend/src/views/Gallery/Collection.vue
Add again the ability to set custom covers for collections that were removed in #1562.
Also added the platform icon in the list view of a collection
=> fix: Custom covers for collections

backend/endpoints/sockets/scan.py, backend/handler/scan_handler.py, frontend/src/components/Details/Title.vue, frontend/src/components/Gallery/AppBar/Platform/Base.vue, frontend/src/components/Gallery/AppBar/Platform/PlatformInfoDrawer.vue, frontend/src/components/Gallery/AppBar/Search/PlatformSelector.vue, frontend/src/components/Settings/LibraryManagement/Dialog/CreatePlatformBinding.vue, frontend/src/components/Settings/LibraryManagement/Dialog/CreatePlatformVersion.vue, frontend/src/components/Settings/LibraryManagement/Dialog/DeletePlatformBinding.vue, frontend/src/components/Settings/LibraryManagement/Dialog/DeletePlatformVersion.vue, frontend/src/components/Settings/LibraryManagement/PlatformBindCard.vue, frontend/src/components/common/Game/Card/Base.vue, frontend/src/components/common/Game/Dialog/UploadRom.vue, frontend/src/components/common/Navigation/ScanBtn.vue, frontend/src/components/common/Navigation/SettingsDrawer.vue, frontend/src/components/common/Platform/Card.vue, frontend/src/components/common/Platform/Dialog/DeletePlatform.vue, frontend/src/components/common/Platform/Icon.vue, frontend/src/components/common/Platform/ListItem.vue, frontend/src/stores/scanning.ts, frontend/src/views/Scan.vue
When using PLATFORM_VERSIONS, this PR sets the `platform.slug` to the "real" metadata slug, instead of the `fs_slug`. It also updates the `platform-icon` component to try and load the `fs_slug` first, then fallback to the `slug`, then finally the default icon. All of this allows us to display the custom `.ico` for bindings and versions, while allowing users to play the system with emulatorjs. Also fixes the logout button visibility on mobile.
=> [ROMM-1616] Support custom icons for platform versions

backend/endpoints/rom.py, backend/endpoints/sockets/scan.py, backend/handler/scan_handler.py, backend/models/rom.py, frontend/src/components/Gallery/FabOverlay.vue, frontend/src/components/common/Game/AdminMenu.vue
This PR fixes the partial metadata scan. If any of the sources already have metadata it will remain in the database.
Also, the ``refresh metadata`` option (in rom admin menu and fab menu) is considered as ``partial-metadata`` scan to refres metadata from any source that doesn't have metadata
=> fix: Partial metadata scan

backend/config/__init__.py, docker/init_scripts/init, env.template
The `WEB_CONCURRENCY` environment variable is a more common way to configure the number of workers for Gunicorn [1] or other web servers.
This change maintains `GUNICORN_WORKERS` compatibility, while notifying users that it is deprecated and should be replaced with `WEB_CONCURRENCY`.
It would also allow us to replace Gunicorn with another web server in the future without changing the variable name.
[1] https://docs.gunicorn.org/en/stable/settings.html#workers
=> misc: Add support for WEB_CONCURRENCY environment variable

docker/Dockerfile, docker/init_scripts/docker-entrypoint.sh, docker/nginx/default.conf, docker/nginx/templates/default.conf.template
Using the `envsubst` command, we can replace environment variables in the nginx template files. This allows for more flexibility when configuring the nginx server.
The Docker image we use as base for Nginx does provide the `20-envsubst-on-templates.sh` script that will replace environment variables in the template files.
This change does not include any behavior change, but unblocks future changes that require environment variables in the nginx configuration.
=> misc: Use nginx templates to allow for environment variable usage

docker/init_scripts/docker-entrypoint.sh, docker/nginx/templates/default.conf.template
By using the `ROMM_PORT` environment variable, users can now configure the port on which the application listens, which defaults to `8080`.
Closes #611.
=> feat: Allow configuring app port using ROMM_PORT environment variable

docker/nginx/templates/default.conf.template
Warning triggered by [gixy](https://github.com/yandex/gixy).
Related documentation:
https://github.com/yandex/gixy/blob/master/docs/en/plugins/aliastraversal.md
=> fix: Nginx alias_traversal warning

docker/init_scripts/docker-entrypoint.sh
When using a custom `ROMM_BASE_PATH`, the symbolic links used by nginx to serve assets were not being updated to point to the correct location, and always used the default `/romm` base path.
This change introduces a fix in the `docker-entrypoint.sh` script, so those symbolic links are updated to point to the correct location set by the `ROMM_BASE_PATH` environment variable.
Fixes #1626.
=> fix: Support for assets when using custom ROMM_BASE_PATH

backend/endpoints/rom.py
Fix how the m3u file is built when not in DEV_MODE
=> fix: build m3u file if not DEV_MODE

docker/nginx/templates/default.conf.template
The nginx configuration was not updated to use the `ROMM_BASE_PATH` environment variable when serving the library files.
We no longer hardcode the base path to `/romm`, but instead use the provided path.
=> fix: nginx configuration for library access when ROMM_BASE_PATH is set

docker/Dockerfile
As the container entrypoint runs `envsubst` to replace environment variables in the nginx configuration files, the `/etc/nginx/conf.d` and its contents must be writable by everyone.
This is needed because a user can set a custom UID/GID to run the container, and the `envsubst` command will run as that user.
=> fix: Make nginx configuration files writable by everyone

backend/config/__init__.py, backend/endpoints/rom.py
For client_id/client_secret combinations, and API keys, we are certain that they should not have leading/trailing whitespaces. We can strip them to avoid any potential issues for users who might have added them incorrectly in their Docker Compose configuration.
This change does NOT affect users/passwords, where leading/trailing whitespaces might be intentional and valid.
=> misc: Strip environment variables related to third-party credentials

backend/endpoints/rom.py
When trying to download a game that is contained in a folder, but is single-file (what we consider "non-multi" game), the download would fail, trying to make nginx proxy the folder instead of that single file.
This commit removes custom logic related to `multi` games, so the logic ends up executing the `if len(files) == 1` block, which is the correct one for single-file games.
A simple way to reproduce this issue is to create a game folder with a single file inside it, and try to download or run EmulatorJS with that game. Both `DEV_MODE=true` and `DEV_MODE=false` were failing in this scenario.
Fixes #1644.
=> fix: Download for single-file games in folder

backend/endpoints/sockets/scan.py, backend/handler/metadata/igdb_handler.py, frontend/src/views/Gallery/Collection.vue, frontend/src/views/Gallery/Platform.vue, frontend/src/views/Gallery/Search.vue
* Remove nonexistent fields for IGDB platform version endpoint
* Run scans in the main app thread in dev mode.
* Fix scroll loading more on mobile
=> [HOTFIX] Misc fixe for alpha.7

backend/endpoints/rom.py, frontend/src/components/common/Game/Dialog/MatchRom.vue
We should be passing in the `urlCover` in all cases and fallback to the metadata values.
Fixes #1742 
=> [ROMM-1742] Fix updating cover when manual matching

frontend/src/views/Player/EmulatorJS/Base.vue, frontend/src/views/Player/RuffleRS/Base.vue
The`<v-row>` needs to expand to its full height to display the game when not in fullscreen mode.
Fixes #1726 
=> [ROMM-1726] Fix ruffle hidden in non-fs mode

frontend/src/views/Player/EmulatorJS/Player.vue
This PR disables the quick save/load buttons, and the ability to switch quick save/load slots. These options can't be synced to the server and don't persist after reload (check demo.emulatorjs.org for default behavior), and their presence is confusing users.
=> Hide save slot settings from menu

backend/endpoints/rom.py, backend/models/rom.py
This PR centralized the login for generating multi-file-download-filenames under `RomFile.file_name_for_download`, and fixes a bug that makes the folder invisible when downloaded on Windows (also tested on macOS).
=> [HOTFIX] Fix dowbnloading multi-files in windows

frontend/src/locales/de_DE/play.json, frontend/src/locales/en_GB/play.json, frontend/src/locales/en_US/play.json, frontend/src/locales/es_ES/play.json, frontend/src/locales/fr_FR/play.json, frontend/src/locales/ja_JP/play.json, frontend/src/locales/ko_KR/play.json, frontend/src/locales/pt_BR/play.json, frontend/src/locales/ro_RO/play.json, frontend/src/locales/ru_RU/play.json, frontend/src/locales/zh_CN/play.json, frontend/src/views/Player/EmulatorJS/Base.vue, frontend/src/views/Player/EmulatorJS/CacheDialog.vue
Our emulatorjs changes sometimes require users to clear IndexDB, so we add a simple button and warning dialog that does just that.
=> Easy way to clear emulatorjs cache via the UI

backend/endpoints/rom.py, backend/utils/nginx.py
Update Content-Disposition headers to allow for proper filenames when downloading via Safari on Mac & iPhone
@DebugDax
Fixes #1810 
=> [HOTFIX] Update content-disposition headers

frontend/src/components/Gallery/AppBar/Base.vue, frontend/src/components/Gallery/AppBar/Search/SearchTextField.vue, frontend/src/components/Gallery/AppBar/common/CharIndexBar.vue, frontend/src/components/Gallery/AppBar/common/FilterDrawer/Base.vue, frontend/src/components/Gallery/AppBar/common/FilterTextField.vue, frontend/src/components/Gallery/Skeleton.vue, frontend/src/views/Gallery/Collection.vue, frontend/src/views/Gallery/Platform.vue, frontend/src/views/Gallery/Search.vue
Search input will always be visible, but filter input will move to sidebar when on mobile. Also removed the search button, now any change in the input will trigger a search/filter, with 500ms debounce.
**Checklist**
|<img width="423" alt="Screenshot 2025-04-10 at 9 26 03 AM" src="https://github.com/user-attachments/assets/bdde4a74-cbfb-4e69-8632-11304a10175d" />|<img width="421" alt="Screenshot 2025-04-10 at 9 26 10 AM" src="https://github.com/user-attachments/assets/730e99f6-9351-4d65-80e6-a4933cedbf86" />|
|---|---|
=> [FIX] Improved handing of search inputs on mobile

backend/endpoints/rom.py, backend/endpoints/tests/test_rom.py, frontend/src/components/common/Game/Dialog/EditRom.vue, frontend/src/components/common/Game/Dialog/MatchRom.vue, frontend/src/services/api/rom.ts
This PR simply passes the new filename to the endpoint, when updating the filesystam name of a game (file or folder). Also removes `rename_as_source` as a param on the update endpoint.
Fixes #1846 1846
**Checklist**
=> [ROMM-1846] Rename file from client input

backend/alembic/versions/0038_add_ssid_to_sibling_roms.py, frontend/src/components/Details/Info/FileInfo.vue
This PR adds `ss_id` to the SQL query when building the `sibling_roms` view by replacing the existing view, with a downwards migration that returns the old one.
**Checklist**
=> [ROMM-1845] Sibling roms should include ss_id

backend/handler/filesystem/base_handler.py, backend/handler/filesystem/firmware_handler.py, backend/handler/filesystem/roms_handler.py, backend/handler/filesystem/tests/test_fs.py
This PR finally puts `EXCLUDED_MULTI_PARTS_FILES` and `EXCLUDED_MULTI_PARTS_EXT` by skipping matched file names and extensions.
Fixes #1849 
**Checklist**
=> [ROMM-1849] Fix excluding files in multi-file ROM

backend/handler/metadata/ss_handler.py
If there's no cover from `us` region, fallback to the `ss` region for URL cover image. Also refactors each field out into its own block for better readability.
**Checklist**
=> [ROM-1847] Use ss region covers as fallback

backend/endpoints/rom.py, backend/handler/metadata/moby_handler.py, backend/handler/metadata/ss_handler.py, frontend/src/components/common/Game/Dialog/MatchRom.vue
This PR removes `slug` from the return value of an `SSRom` and `MobyRom`, since the value is a) useless and b) can override the value we use to link to the game in IGDB.
Fixes #1770 
**Checklist**
=> [ROMM-1770] Stop squashing old metadata props when manually matching

backend/handler/filesystem/resources_handler.py
During a scan, if an image fails to be read, the scan is aborted and only one game is added to the library.
To work around this, you need to manually change the image and re-scan for every game that this affects.
I've validated that this works for me by changing my docker file directly. The scan completes fully.
**Checklist**
=> During a scan, if an image fails to be read, the scan is aborted

backend/handler/database/roms_handler.py, frontend/src/components/common/Game/Table.vue
Handle the case when ordering by `fs_size_bytes` as a one-off.
Fixes #1894 
**Checklist**
=> [ROMM-1894] Support sorting games by file size

backend/handler/auth/base_handler.py
Fix for OIDC new user logins getting a "Internal Server Error" message on first login. This handles the new user database object properly, so that further updates to it (like when updating the last login and last active times) successfully happen.
Sorry for the second pull request.  Realized I had the wrong branch on the first submitted one and it wouldn't let me fix it properly...
**Checklist**
Not sure who to add as reviewers as I am new here.
Partially/fully fixes #1502
=> fix: correct user creation logic in OpenIDHandler

backend/endpoints/rom.py, backend/handler/database/roms_handler.py, frontend/src/components/Details/RetroAchievements.vue, frontend/src/components/Details/Title.vue, frontend/src/components/Gallery/AppBar/common/FilterDrawer/Base.vue, frontend/src/components/Gallery/AppBar/common/FilterDrawer/FilterRaBtn.vue, frontend/src/locales/de_DE/platform.json, frontend/src/locales/en_GB/platform.json, frontend/src/locales/en_US/platform.json, frontend/src/locales/es_ES/platform.json, frontend/src/locales/fr_FR/platform.json, frontend/src/locales/it_IT/platform.json, frontend/src/locales/ja_JP/platform.json, frontend/src/locales/ko_KR/platform.json, frontend/src/locales/pt_BR/platform.json, frontend/src/locales/ro_RO/platform.json, frontend/src/locales/ru_RU/platform.json, frontend/src/locales/zh_CN/platform.json, frontend/src/services/api/rom.ts, frontend/src/stores/galleryFilter.ts
This PR add a new filter to show RA compatible roms only
**Checklist**
=> feat: add Retroachievements filter to show only RA compatible games

backend/adapters/services/rahasher.py, backend/handler/filesystem/roms_handler.py
The core of this change is using the `folder/*` syntax when running the contents of a folder thought rahasher, plus searching all output lines for a matching hash. Parsing compressed files is still not supported.
**Checklist**
=> [HOTFIX] Fix ramatcher on mult-file games

backend/alembic/versions/0041_assets_t_thumb_cleanup.py, backend/endpoints/sockets/scan.py, backend/handler/scan_handler.py
Lingering `t_thumb` values in `url_cover` and `url_screenshots` will cause romm to overrite cover and screenshot art with thumbnails on partial scans. This replaces all uses of `t_thumb` in those fields with `t_1080p` for covers and `t_720p` for screenshots. Tested on both mariadb and postgres locally.
Some `cover_url` fields in `igdb_metadata` might still use `t_thumb` and would still be affected, but there's no easy way top clean those up through SQL.
**Checklist**
=> Cleanup lingeting t_thumb in cover and screenshto art

backend/exceptions/endpoint_exceptions.py
These critical log messages are unnecessary and can clutter the logs, based on user requests. This is even more notorious when RomM is integrated to an error tracking system like Sentry.
**Checklist**
=> fix: Remove critical log messages for 403 and 404 exceptions

frontend/src/components/Details/RetroAchievements.vue, frontend/src/components/Details/Title.vue
* Add a link to the game page in the RetroAchievements chip in the title.
* Add links to the achievement pages in the achievement badges.
* Fix the RetroAchievements chip to correctly display the RA logo.
**Checklist**
=> misc: Add RetroAchievements links to game and achievement badges

backend/adapters/services/retroachievements_types.py, backend/handler/metadata/ra_handler.py
Include detailed type information for RetroAchievements API responses, based on the official API documentation.
**Checklist**
=> misc: Add typing to RetroAchievements API responses

backend/adapters/services/retroachievements.py, backend/handler/metadata/ra_handler.py
Add a new service adapter for the RetroAchievements API, to separate concerns with RomM's handler for metadata. This adapter is agnostic to the handler and only provides methods to interact with the API, and correctly return typed responses.
The API authorization was also improved to be handled by a specific `httpx.Auth` class that sets the `y` parameter for each request.
**Checklist**
=> misc: Create RetroAchievements service adapter

poetry.lock, pyproject.toml
The breaking code in `streaming-form-data` has been fixed, and Poetry also was patched based on @gantoine's proposed fix. This allows us to use the official releases again instead of a fork.
**Checklist**
=> misc: Move back to upstream streaming-form-data dependency

backend/adapters/services/retroachievements.py, backend/adapters/services/retroachievements_types.py, backend/handler/metadata/ra_handler.py
Iterate through all pages of user completion progress in the RetroAchievements service, instead of limiting the data retrieval to the first 500 results.
**Checklist**
=> fix: Iterate through user completion progress in RetroAchievements

docker/Dockerfile
Bump `RALibretro` to the latest commit from the upstream repository. Removes the need to use an older version of Alpine Linux, but requires some changes to the `RALibretro` source code to compile successfully.
The `nginx` image is still not available for Alpine 3.22, but we can also upgrade to its latest patch version (`1.27.5`).
**Checklist**
=> misc: Upgrade RALibretro to the current upstream version

README.md
Nothing like a new user to break the docs :rofl:
Existing link is 404, I believe this is the correct link?
=> Fix Retroachievements URL in README

docker/init_scripts/init
The `GUNICORN_WORKERS` environment variable has been deprecated in favor of `WEB_CONCURRENCY`.
**Checklist**
=> misc: Remove support for deprecated GUNICORN_WORKERS variable

backend/endpoints/rom.py, backend/handler/database/roms_handler.py
These parameters were replaced by optional versions that allow for more flexibility. This change removes code already marked as deprecated.
**Checklist**
=> misc: Remove deprecated boolean parameters from get_roms endpoint

backend/handler/metadata/ra_handler.py
This logic was moved to the RetroAchievements service in #1951.
**Checklist**
=> misc: Remove _request method from RAHandler

backend/handler/database/roms_handler.py, backend/handler/tests/test_db_handler.py
These methods are no longer used in the codebase and have been removed to clean up the code.
**Checklist**
=> misc: Remove unused methods from Roms handler

frontend/src/components/Details/Personal.vue
Stop bombarding the API with updates when editing personal data, like notes (which currently trigger an API call on each keystroke), and status (e.g. changing values on the "Completion %" slider triggers an API call on each change).
This change introduces a debounce of 500ms before sending updates to the API.
**Checklist**
=> fix: Add debounce to RomUser changes

Dockerfile, docker/Dockerfile
The previous attempt to upgrade RALibretro before a new tagged version was available (#1970) needed to be reverted, as the RAHasher tool failed with segmentation faults in some scenarios.
**Checklist**
=> misc: Upgrade RALibretro to v1.8.1

frontend/src/utils/index.ts, frontend/src/views/Player/EmulatorJS/Base.vue
As implemented in EmulatorJS.org:
https://github.com/EmulatorJS/EmulatorJS/blob/f679b265e9104b9038cc664e00a6840b47df191c/data/src/emulator.js#L47
**Checklist**
=> fix: Require threads for dosbox_pure core

backend/watcher.py, pyproject.toml, uv.lock
The `watchdog` observer supports filtering events based on their type, so unwanted events don't get dispatched.
**Checklist**
=> fix: watchdog: Only subscribe to relevant filesystem events

pyproject.toml, uv.lock
The latest minor version `0.116` of FastAPI changes the `standard` extra to include extra dependencies to deploy to FastAPI Cloud, which we don't need.
This change moves to the new `standard-no-fastapi-cloud-cli` extra, which maintains the previous set of dependencies.
**Checklist**
=> misc: Upgrade FastAPI to v0.116

frontend/src/components/Details/Info/GameInfo.vue, frontend/src/components/Details/Title.vue
Launchbox expects you to use the `games/dbid` path, which will redirect to the correct game on the website.
https://forums.launchbox-app.com/topic/61820-any-chance-we-could-make-the-games-db-urls-match-the-database-game-ids/
Fixes #2107 
**Checklist**
=> [ROMM-2107] Fix launchbox URL

docker/nginx/templates/default.conf.template
Add IPv6 support
This change adds IPv6 support to the nginx running in the docker container. This allows people to access RomM over IPv6 if they want.
**Checklist**
=> Add IPv6 support

backend/handler/scan_handler.py, backend/tasks/scheduled/scan_library.py, backend/tasks/tests/test_scan_library.py
The existing code incorrectly maps boolean flags to metadata sources, leading to colliding `True` keys in the dictionary. This caused only one metadata source to be recognized during scheduled scans, even when multiple sources were enabled.
**Checklist**
=> fix: Correctly evaluate enabled metadata sources in scheduled library scan

backend/alembic/versions/0048_sibling_roms_more_ids.py, backend/handler/database/roms_handler.py
This PR adds more metadata providers to sibling ROM grouping, and fixes(?) missing ROMs from collections (somehow...).
Fixes #1868 
**Checklist**
=> [ROMM-1868] Fix grouping by metadata rows

frontend/src/components/Gallery/AppBar/common/FilterDrawer/Base.vue, frontend/src/views/Gallery/Search.vue, frontend/src/views/Settings/LibraryManagement.vue
Small improvements to search where the filter drawer fires a fetch event on mount of any of the filters are present in the URL.
**Checklist**
=> Fire off search if URL state prepopulated

frontend/src/components/Details/Title.vue, frontend/src/components/Gallery/AppBar/common/FilterDrawer/Base.vue, frontend/src/views/Gallery/Platform.vue, frontend/src/views/Scan.vue, frontend/src/views/Settings/LibraryManagement.vue
Use `filteredPlatforms` for most uses of `allPlatforms`, which filters empty platforms (even on scan page).
Fixes #2211 
**Checklist**
=> [ROMM-2211] Only show missing platforms on lib manage page

Dockerfile, backend/handler/filesystem/roms_handler.py, backend/utils/archive_7zip.py, docker/Dockerfile, frontend/src/components/Details/States.vue, frontend/src/views/Gallery/Collection/BaseCollection.vue, frontend/src/views/Gallery/Search.vue, pyproject.toml, uv.lock
`py7zr` adds 30MB+ to the image size in useless dependencies for "compatibility". This PR replaces it with the native `7zip/p7zip` library, opting to call sub-processes and parse the output.
**Checklist**
=> Use native 7z to extract files and calculate hashes

uv.lock
Update `rq-scheduler` fork to remove the unnecessary dependency on `freezegun`.
**Checklist**
=> misc: Remove indirect dependency freezegun

docker/Dockerfile, docker/init_scripts/init
* Added `linux-headers` back, but only for development stage.
* Fixed initialization script, as `uv` is not included in the final Docker image.
* Initialize variable `ENABLE_SCHEDULED_UPDATE_LAUNCHBOX_METADATA`.
**Checklist**
=> fix: Docker build and init fixes

backend/config/__init__.py, backend/config/config_manager.py
This change adds a new environment variable `DB_QUERY_JSON` that allows users to specify querystring values for additional database connection parameters. This is useful for passing custom query parameters to the database connection URL.
The `DB_QUERY_JSON` variable should contain a JSON string with key-value pairs of strings, which is the required format for the SQLAlchemy URL `query` parameter. If the variable is not set, no additional query parameters will be added to the database connection URL.
Closes #2093.
**Checklist**
=> feat: Add support for database query string using DB_QUERY_JSON variable

backend/endpoints/saves.py, backend/endpoints/screenshots.py, backend/endpoints/states.py, backend/handler/database/screenshots_handler.py, backend/models/assets.py, backend/tests/handler/test_db_handler.py
When retrieving the related screenshot for a `Save` or `State`, we were retrieving a very heavy representation of the associated `Rom` object, only to iterate through its screenshots to find the one we needed.
This change modifies the `Save` and `State` models to directly query the `Screenshot` model, which is much faster and more efficient. The `DBScreenshotsHandler` has been updated to include a new `filter` method that will simplify building queries using SQLAlchemy, something we can extend to other handlers in the future.
Fixes #1925.
**Checklist**
=> fix: Improve performance on asset screenshot retrieval

backend/watcher.py, docker/init_scripts/init
Run file watcher using `opentelemetry-instrument` to enable tracing for the watcher service.
**Checklist**
=> feat: Add OpenTelemetry integration to file watcher

backend/handler/metadata/base_hander.py, backend/models/firmware.py, backend/startup.py, backend/tests/handler/metadata/test_base_handler.py, backend/tests/utils/test_cache.py, backend/utils/cache.py, docker/init_scripts/init
Guarantee that cache is initialized during startup, and only once, instead of every time a `MetadataHandler` object is instantiated.
Also, improve logic to determine `fixtures` paths.
**Checklist**
=> misc: Move cache initialization to startup script

backend/config/__init__.py, docker/init_scripts/init, entrypoint.sh
Tested locally by logging in/out. Also exec's into the container to ensure that the `ROMM_AUTH_SECRET_KEY` set in `.env` was still being used.
**Checklist**
=> Make default ROMM_AUTH_SECRET_KEY consistent between workers

backend/endpoints/user.py, backend/handler/metadata/ra_handler.py, frontend/src/__generated__/models/RAUserGameProgression.ts, frontend/src/components/Settings/UserProfile/RetroAchievements.vue, frontend/src/services/api/user.ts
This change makes the RetroAchievements progression sync endpoint to optionally perform an incremental sync (when `incremental` is true), by only fetching new achievements since the last sync.
This reduces the amount of data fetched and speeds up the sync process for users who frequently sync their progression. It unblocks the implementation of automatic periodic syncs in the future.
Frontend behavior:
- When the `Apply` button is clicked in the RetroAchievements settings, a full sync is performed (same as before). This is because a change to the RA username may have occurred.
- When the `Sync` button is clicked, an incremental sync is performed.
**Checklist**
=> feat: Add incremental sync for RetroAchievements progression

backend/adapters/services/igdb.py, backend/adapters/services/igdb_types.py, backend/handler/metadata/igdb_handler.py, backend/tests/conftest.py, backend/tests/handler/cassettes/test_fastapi/test_scan_rom.yaml
Add a new service adapter for the IGDB API, to separate concerns with RomM's handler for metadata. This adapter is agnostic to the handler and only provides methods to interact with the API, and correctly return typed responses.
The API authorization was also improved to not rely on decorating each method that makes requests, but instead using an `aiohttp` middleware to automatically add the required headers to each request.
Utils `mark_expanded` and `mark_list_expanded` where added to help narrow the types of IGDB's expandable fields when we know they are expanded, for `mypy` type checking.
**Checklist**
=> misc: Create IGDB service adapter

.devcontainer/dev.env, .devcontainer/devcontainer.json, docker-compose.yml
issue: devcontainer doesn't launch properly as is
problematic code: filepath for docker-compose.yml and not using the existing env.template file
fix: change filepath to refer to root and use env.template in the devcontainer for faster usage
**Checklist**
=> fix devcontainer launch

backend/tests/utils/test_cache.py, backend/utils/cache.py
The cache for fixture files was being set without a TTL, which meant that updates to the fixture files were not reflected in the cache.
This change saves the MD5 hash of the fixture file in a different key, and compares it to the current hash of the file before deciding whether to update the cache.
Fixes #2347
**Checklist**
=> fix: Invalidate fixture cache on file change

docker/nginx/templates/default.conf.template
The COEP (Cross-Origin Embedder Policy) and COOP (Cross-Origin Opener Policy) headers are needed by EmulatorJS to use the `SharedArrayBuffer` feature, and enable multi-threaded cores.
These headers are only being set by Nginx for responses to requests made to the EmulatorJS player path. This is because cross-origin isolation breaks other features in the application (such as YouTube embeds), so we only want to enable it for the EmulatorJS player.
It's important to mention that this change does not work when `DEV_MODE` is set, as we would need Vite server to also set these headers in that case. This could be implemented separately, if needed.
These changes are not enough to enable multi-threaded cores in the frontend. Because our application is a SPA, we also need to ensure …
=> feat: Add COEP and COOP headers for EmulatorJS within Nginx config

frontend/src/console/views/Play.vue, frontend/src/stores/config.ts, frontend/src/views/Player/EmulatorJS/Player.vue
This should stop us wiping the emulatorjs control values (will need to clear localstorage)
**Checklist**
=> [HOTFIX] getEjsControls should return null if no controls for core or default

backend/tests/adapters/services/test_mobygames.py, backend/tests/adapters/services/test_screenscraper.py, backend/tests/adapters/services/test_steamgriddb.py, backend/tests/utils/test_cache.py
Fixes warnings triggered by unawaited coroutines in test cases.
- Before: `552 passed, 1 skipped, 78 warnings`
- After: `552 passed, 1 skipped, 61 warnings`
**Checklist**
=> fix: Correctly mock async response.json() in unit tests

backend/config/config_manager.py, backend/endpoints/configs.py, backend/endpoints/responses/config.py, backend/tests/config/fixtures/config/config.yml, backend/tests/config/test_config_loader.py, examples/config.example.yml, frontend/src/__generated__/models/ConfigResponse.ts, frontend/src/components/common/Navigation/ConsoleModeBtn.vue, frontend/src/console/views/Play.vue, frontend/src/stores/config.ts, frontend/src/views/Player/EmulatorJS/Player.vue
This PR sets `EJS_CacheLimit`, the cache limit per-game, in bytes (default value is 1GB).
Fixes #2336 
**Checklist**
=> [ROMM-2336] Config entry for EJS_CacheLimit

DEVELOPER_SETUP.md
* DEVELOPER_SETUP.md formatting was broken, and the second half was considered to be code.
=> Fix Markdown formatting of DEVELOPER_SETUP.md

backend/adapters/services/mobygames.py, backend/adapters/services/retroachievements.py, backend/adapters/services/screenscraper.py, backend/adapters/services/steamgriddb.py, backend/endpoints/heartbeat.py, backend/endpoints/responses/heartbeat.py, backend/handler/metadata/flashpoint_handler.py, backend/handler/metadata/hasheous_handler.py, backend/handler/metadata/hltb_handler.py, backend/handler/metadata/igdb_handler.py, backend/handler/metadata/launchbox_handler.py, backend/handler/metadata/moby_handler.py, backend/handler/metadata/playmatch_handler.py, backend/handler/metadata/ra_handler.py, backend/handler/metadata/sgdb_handler.py, backend/handler/metadata/ss_handler.py, backend/handler/metadata/tgdb_handler.py, backend/tests/endpoints/test_heartbeat.py, frontend/src/__generated__/models/MetadataSourcesDict.ts, frontend/src/components/common/Navigation/SettingsDrawer.vue, frontend/src/plugins/router.ts, frontend/src/stores/heartbeat.ts, frontend/src/views/Auth/Setup.vue, frontend/src/views/Settings/MetadataSources.vue
This PR adds a new metadata sources admin page that displays the status and configuration of all supported metadata sources/scrapers. The new `/heartbeat/metadata` endpoint makes requests to each metadata provider to test to connection (where relevant).
Fixes #2438 
**Checklist**
=> [ROMM-2438] Add metadata sources admin page

backend/endpoints/responses/rom.py, backend/endpoints/rom.py, backend/endpoints/sockets/scan.py, backend/handler/filesystem/roms_handler.py, backend/handler/scan_handler.py, backend/models/rom.py, backend/tests/handler/filesystem/test_roms_handler.py, backend/tests/handler/test_fastapi.py, frontend/src/__generated__/models/DetailedRomSchema.ts, frontend/src/__generated__/models/SimpleRomSchema.ts, frontend/src/components/Details/Info/FileInfo.vue, frontend/src/components/common/Game/Dialog/DeleteRom.vue, frontend/src/components/common/Game/Dialog/EditRom.vue, frontend/src/views/Player/EmulatorJS/Base.vue
* has_simple_single_file: single file, non-nested
* has_nested_single_file: single file, nested under a parent folder
* has_multiple_files: multiple files, obviously nested
**Checklist**
=> Split `rom.multi` into more specific fields

backend/models/base.py, frontend/src/utils/index.ts
=> [ROMM-2416] Use python timezone aware datetime as defaults for created_at/updated_at

backend/config/__init__.py, backend/endpoints/heartbeat.py
This adds an option to disable the setup wizard. The intended use for this is in combination with `DISABLE_USERPASS_LOGIN = true`, `OIDC_ENABLED = true`, and `OIDC_CLAIM_ROLES != ''`. In this situation there is virtually no point in defining the initial admin user; you won't be able to log in with it directly, and if it matches the email you log in with using OIDC your roles will be set based on the role mapping.
The only purpose this initial account could serve at this point is recovery in case OIDC login breaks. I'm personally not concerned about this scenario since OIDC is configured through the environment, so you won't actually need to log in to fix this. Still, I think it's a good idea for people to opt in to this so that they can make this choice for themselves. …
=> Add option to disable setup wizard

backend/decorators/auth.py
Adds OIDC_CLAIM_ROLES to the requested scope in order for it to be filled in the token userinfo.
<sup>Authelia doesn't add the OIDC_CLAIM_ROLES to the token userinfo unless requested in the scope.</sup>
**Checklist**
=> Add OIDC_CLAIM_ROLES to the requested scope in order for it to be filled in the token userinfo
