changelog.md, readme.md
=> merge develop into master

backend/src/config/__init__.py, backend/src/handler/igdb_handler.py, backend/src/main.py, backend/src/utils/fastapi.py, backend/src/utils/fs.py, frontend/src/components/Navigation.vue, frontend/src/components/RomDetails.vue
Smart scan added:
- Now RomM only take the changes made in the filesystem, making the scan much faster
=> smar scan [platforms+games]

changelog.md
- Now game files can be renamed after the name matched in IGDB, keeping the tags.
=> v1.6 changelog

.github/actions/build.sh, .github/workflows/image.yml, docker/Dockerfile
- Optimize Dockerfile layers, reduce from 23 to 15
- Remove software dependencies unneeded, reduce Docker image size by 200MB (660 -> 460)
- Rework GitHub Workflow by using Actions
- Push image to GHCR as alternative to Docker Hub
=> Optimize Dockerfile and build workflow

README.md
README platforms support list updated with the new platforms added in [v1.8.3](https://github.com/zurdi15/romm/releases/tag/v1.8.3)
=> platforms support list updated

frontend/src/views/Gallery.vue
Gallery view is now more responsive in grid and list views
=> Fix grid + list scroll

backend/endpoints/scan.py, backend/utils/fs.py, frontend/src/views/library/Scan.vue
Fixed scanning multipart roms, RomM wasn't detecting the roms path correctly.
=> Multipart roms scan fixed

backend/handler/igdb_handler.py, frontend/src/App.vue, frontend/src/components/Platform/PlatformCard.vue, frontend/src/components/Platform/PlatformListItem.vue, frontend/src/views/library/Scan.vue
Now RomM is case-insensitive to platforms folder names, improving flexibility
* Now platforms folders are case insensitive, allowing to have them lowercase or uppercase
* Fixed platforms drawer to dissapear after scan
Fixes #282
=> Fix case sensitive platforms

.gitignore, backend/endpoints/scan.py, backend/utils/fastapi.py, frontend/src/components/Game/Card/ActionBar.vue, frontend/src/components/Game/ListItem/Item.vue, frontend/src/views/Details.vue, frontend/vite.config.js
* Fix crash when game not found in IGDB during scan
* Revert back to direct-download button for single files
=> Hotfix scanning IGDB misses

frontend/src/services/api.js, frontend/vite.config.js
* Adds the downloads path to the ignore list for the service worker
* Add a 60s timeout for error/cancelled downloads
=> Hotfix downloading multi-files

SECURITY.md
Adding this in preparation for the release of 2.0
=> Add a SECURITY.md policy

backend/endpoints/rom.py, frontend/src/components/Dialog/Rom/EditRom.vue
Also limit uploads to .png files in the UI
Fixes #377
=> [ROMM-377] Prevent overwrite of custom cover art

backend/handler/igdb_handler.py
In the event the first call to IGDB times out, pass so we can try it again.
Fixes #375
=> [ROMM-375] Catch request timeouts to IGDB

CHANGELOG.md, README.md
Added some doc about the authentication system in the readme.md
=> merge master into release

frontend/src/views/Login.vue
This PR adds a loader for the login button for better feedback in slower systems.
=> loader adding to login btn

backend/endpoints/tasks.py, backend/endpoints/tests/test_heartbeat.py, backend/main.py, backend/tasks/update_mame_xml.py, backend/utils/oauth.py, frontend/src/components/Settings/General/TaskStatus/TaskStatusCard.vue, frontend/src/stores/auth.js
Also updates the URL of the MAME task to a hosted gist.
Closes #437
=> [ROMM-437] Button to manually run all tasks

frontend/src/components/Dialog/Rom/DeleteRom.vue
=> [ROMM-466] Reset delete from fs when dialog closed

frontend/src/components/Details/ActionBar.vue, frontend/src/components/Game/Card/ActionBar.vue, frontend/src/views/Details/Base.vue
Some users have been having issues with direct-download of single file games. This PR attempts to fix those issues by having all downloads go through the api endpoint.
Closes #471
=> [ROMM-471] Send all downloads to endpoint

backend/endpoints/scan.py, frontend/src/components/Details/Title.vue, frontend/src/components/Game/Card/Cover.vue
Seems the `try...catch` was wrapping the wrong function call
Closes #460
=> [ROMM-460] Continue scanning after exception

frontend/src/plugins/vuetify.js
When setting up RomM, the default theme is not being checked properly from localStorage.
=> Fixed default theme in first setup

.github/workflows/build.yml, .github/workflows/pytest.yml, .vscode/tasks.json, DEVELOPER-SETUP.md, backend/__version__.py, backend/endpoints/tests/test_heartbeat.py, backend/main.py, backend/utils/__init__.py, backend/utils/fs.py, backend/utils/tests/test_fs.py, docker/Dockerfile, frontend/package.json, frontend/src/App.vue, frontend/src/components/Settings/General/TaskStatus/TaskStatusCard.vue, frontend/src/stores/heartbeat.js, frontend/src/views/Settings/ControlPanel/Base.vue, pyproject.toml
Now, the ``version`` that is being displayed in the settings panel is being fetch from the backend, allowing to get the version from the ``__version__`` file or the ``branch name`` when RomM is being excuted in a development environment.
|branch name|version|
|----|----|
|![localhost_3000_settings_control-panel (1)](https://github.com/zurdi15/romm/assets/34356590/6023b984-d29e-47a7-b849-3c1dc181bf01)|![localhost_3000_settings_control-panel (2)](https://github.com/zurdi15/romm/assets/34356590/37e5fa75-d025-44f4-a13a-def2e3466837)|
=> Unified romm version entry point

backend/handler/igdb_handler.py
=> [ROMM-503] Shortname support for AES/MVS ssytems

frontend/src/views/Login.vue
=> Better errors on auth page

unraid_template/romm.xml
Unraid template was updated to show the internal RomM port change from `80` to `8080`
=> Update unraid template

backend/config/config_loader.py, backend/endpoints/scan.py, frontend/src/components/Details/Title.vue, frontend/src/components/Game/Card/Cover.vue, frontend/src/components/Game/DataTable/Base.vue
Now the error message when users bind the `config.yml` file without create it before setting up RomM is clearer.
Also introduced little front tweaks.
=> Config file error management improved

README.md
=> Change helm-chart url to point to artifacthub.io landing page

backend/endpoints/scan.py
=> Added more logs on scan when no files found

backend/handler/igdb_handler.py
These methods are all `async` so they need to be awaited.
=> Await calls to custom scanners

backend/handler/igdb_handler.py, frontend/src/components/Details/VersionSwitcher.vue
Also falls back to file name if no langs, regions or tags
Closes #554 
cc @Djiit
=> Support for switch update and DLC files

frontend/src/components/Details/ActionBar.vue, frontend/src/components/Details/BackgroundHeader.vue, frontend/src/components/Details/Info.vue, frontend/src/components/Details/Title.vue, frontend/src/components/Drawer/Base.vue, frontend/src/views/Details/Base.vue
Details view was a mess with too much custom css to be responsive caused by a bad design.
Now it was redesigned almost from scratch so it will be more consistent and responsive in the long term
=> Details view revamped and optimized

backend/handler/igdb_handler.py, backend/handler/tests/cassettes/test_get_ps2_opl_rom.yaml
Just check that there's a valid IGDB ID before trying to fetch cover and screenshots
=> Eliminate 400s on cover/screenshot fetch

backend/utils/fs.py, backend/utils/tests/test_fs.py, examples/config.example.yml
https://docs.python.org/3/library/fnmatch.html
=> [ROMM-575] File exclusions accept wildcards

backend/endpoints/platform.py, frontend/src/services/api.ts
Remove platform now search platform by ``slug`` instead of ``fs_slug``
=> Fix remove platform

backend/main.py, backend/utils/__init__.py, frontend/src/components/Drawer/Footer.vue, frontend/src/components/Settings/General/TaskStatus/TaskWatcher.vue
Now when a new version is available a message will pop in the footer of the drawer and will have a link to the release notes.
This feature can be tested locally being in a branch named ``1.0.0`` for example.
=> Checks and shows when a new version is available

README.md
Preview: https://github.com/zurdi15/romm/blob/696c88f37d0b868215d930a8ce5faf729ff1603c/README.md
=> Cleanup and clarify the readme

frontend/src/stores/roms.ts
=> Reorder grouped roms in gallery

.gitignore, DEVELOPER-SETUP.md, backend/config/config_manager.py, backend/config/tests/fixtures/config/config.yml, backend/config/tests/test_config_loader.py, backend/endpoints/config.py, backend/endpoints/responses/config.py, backend/endpoints/responses/search.py, backend/handler/igdb_handler.py, backend/handler/scan_handler.py, backend/handler/tests/cassettes/test_get_platform.yaml, backend/handler/tests/cassettes/test_get_ps2_opl_rom.yaml, backend/utils/tests/cassettes/test_scan_platform.yaml, examples/docker-compose.example.yml, frontend/src/__generated__/index.ts, frontend/src/__generated__/models/ConfigResponse.ts, frontend/src/__generated__/models/IGDBRom.ts, frontend/src/__generated__/models/RomSearchResponse.ts, frontend/src/components/Dialog/Config/CreatePlatformVersion.vue, frontend/src/components/Dialog/Config/DeletePlatformVersion.vue, frontend/src/components/Settings/Config/PlatformVersionsCard.vue, frontend/src/services/api_config.ts, frontend/src/stores/config.ts, frontend/src/types/emitter.d.ts, frontend/src/views/Settings/ControlPanel/Config/Base.vue
This PR adds support for platform versions. For example: ``NAOMI`` as version of ``Arcade``. The association must be configured in the ``config.yml`` file in the new ``system.versions`` section.
Roms in the platform version will be scanned search using in the ``main platform id``  as IGDB doesn't provide games for api calls for platform versions.
Now ``config.yml`` file must be placed inside a ``config`` folder and bind it as follows to docker: ``/path/config:/romm/config`` and if the ``config.yml`` file doesn't exists it will be created empty automatically.
Closes #569 
Closes #609 
WIP:
=> Platforms versions support

backend/endpoints/raw.py, backend/endpoints/responses/rom.py, backend/endpoints/rom.py, backend/endpoints/webrcade.py, backend/models/rom.py, examples/docker-compose.example.yml, frontend/src/__generated__/models/RomSchema.ts, frontend/src/components/Details/ActionBar.vue, frontend/src/components/Game/Card/ActionBar.vue, frontend/src/components/Game/DataTable/Base.vue, frontend/src/services/api/index.ts, frontend/src/utils/index.ts, frontend/src/views/Play/Player.vue
* Use existing content endpoint to fetch roms
* Support leading zipped multi-file roms
* Also load .m3u file with assets
* Add tooltip for disabled games as "not currently supported"
=> Multi-file emulation support

backend/alembic/versions/0014_asset_files.py, backend/models/rom.py, backend/watcher.py, frontend/src/views/Details/Base.vue
``Aditional content`` and ``related games`` tabs were showing all the time.
=> Fixed aditional content tab

backend/endpoints/sockets/scan.py, backend/handler/db_handler/db_platforms_handler.py, backend/handler/scan_handler.py, backend/handler/tests/test_db_handler.py, backend/watcher.py
* `scan_platforms` expects a list of IDs so make sure we're passing that
* rename `get_platform_by_slug` to `get_platform_by_fs_slug` to clarify what's expected
=> Hotfix scanning via watcher

backend/handler/fs_handler/fs_resources_handler.py
No need for an RC4, this can go out when 3.0 goes live
=> Hotfix storing screenshots when igdb fetch fails

README.md
New wiki pages means a general cleanup of the readme
=> More more content to the wiki

.gitignore, backend/endpoints/tasks.py, docker/Dockerfile, docker/init_scripts/init, examples/docker-compose.example.yml
* set the directly for  redis data when running redis-server
* add volume bind for redis data persistence
* fixes endpoint for running all tasks manually from the config page
* add random `romm_test` folder that keeps appearing to gitignore
=> Redis data volume bind

backend/handler/igdb_handler.py
=> Revert "Normalize rom names when parsing exact matches (remove diacritics & special characters)"

frontend/src/views/Play/Base.vue, frontend/src/views/Play/Player.vue
=> fix: player overflowing viewport

backend/handler/socket_handler.py, docker/Dockerfile, docker/init_scripts/init, frontend/src/services/api/rom.ts
* Allow setting PUID/GUID/UMASK with environment variables
* Bump alpine image version to onstall python 3.11
* Set folder user/group IDs in `init`
* Fix background scanning after socketio upgrade
* Fix download bug with file names in safari
@psych0d0g you might want to have a look at this
=> Dynamic PUID and GUID

backend/endpoints/rom.py
=> [ROMM-729] Fix content disposition header

frontend/src/views/Settings/ControlPanel/Base.vue, frontend/src/views/Settings/ControlPanel/General/Base.vue
Fixed what can view an user with the ``viewer`` role.
=> Fixed viewer role UI permissions

backend/handler/metadata_handler/igdb_handler.py, backend/handler/metadata_handler/moby_handler.py
=> Fix serach by ID for mobygames

frontend/src/views/Play/Player.vue
=> [ROMM-842] Fix textareas in emujs

frontend/src/components/Game/Card/ActionBar.vue
Play button disabled for not supported platforms outside the gallery view
=> Fixed gallery play btn for not supported platforms

backend/handler/filesystem/base_handler.py, backend/handler/filesystem/firmware_handler.py, backend/handler/filesystem/roms_handler.py, frontend/src/services/api/user.ts
* Fix updating user images
* Ignore firmware files based on config
=> Hotfixes for 3.2 RC1

backend/endpoints/rom.py
https://github.com/rommapp/romm/pull/871
https://github.com/rommapp/romm/pull/865
=> Fix filename error

backend/handler/metadata/igdb_handler.py, backend/handler/metadata/moby_handler.py
This was fixed in #838 but lost during an override of the release branch.
=> [ROMMM-834] Fix search by ID for mobygames

backend/endpoints/responses/platform.py, backend/endpoints/responses/rom.py, backend/handler/database/platforms_handler.py, backend/handler/database/roms_handler.py, backend/handler/database/users_handler.py, backend/logger/logger.py, backend/models/assets.py, backend/models/platform.py, backend/models/rom.py, backend/models/user.py, frontend/src/App.vue, frontend/src/components/Gallery/AppBar/AdminMenu.vue, frontend/src/components/Gallery/AppBar/DeleteBtn.vue, frontend/src/components/Gallery/AppBar/ScanBtn.vue, frontend/src/components/Gallery/AppBar/UploadRomBtn.vue, frontend/src/components/Gallery/AppBar/ViewFirmwareBtn.vue, frontend/src/stores/roms.ts, frontend/src/views/Gallery/Base.vue
Bonus: speedup loading of roms list when user has large number of saves/states/screenshots
=> [HOTFIX] Fix scanning from heartbeat refactor

backend/endpoints/sockets/scan.py, backend/handler/scan_handler.py
=> [ROMM-867] Only scan platform when selected

frontend/src/components/Drawer/Footer.vue, frontend/src/components/Gallery/AppBar/FilterBar.vue, frontend/src/components/Game/Card/Cover.vue, frontend/src/components/Game/DataTable/Base.vue, frontend/src/services/api/rom.ts, frontend/src/stores/roms.ts, frontend/src/types/emitter.d.ts, frontend/src/utils/index.ts, frontend/src/views/Details/Base.vue, frontend/src/views/Gallery/Base.vue
- Changed gallery filters to autocomplete selectors
- Added true pagination to gallery table view
- Added 404 pages for non-existent platforms or roms
- Fetch all roms on load
=> Refactor gallery render

frontend/src/components/Dialog/Loading.vue, frontend/src/components/Game/Card/Cover.vue, frontend/src/views/Gallery/Base.vue
- Fixed gallery render on mobile when scrolling
- Fixed game multiselect on touchscreen when scrolling
=> Gallery render fixed on mobile

docker/Dockerfile
Ran our Dockerfile though GPT 4o asking it to improve everything it can. Redis stuff in untouched since I don't understand it. Tested the output and it works as expected. 🤷🏼
=> GPT'd Dockerfile

backend/alembic/versions/0019_resources_refactor.py, backend/endpoints/rom.py, backend/endpoints/sockets/scan.py, backend/handler/filesystem/resources_handler.py, backend/handler/filesystem/tests/test_fs.py, backend/models/platform.py, backend/models/rom.py
* Better performance of migration
* Refactor resource handler
=> backend tweaks + refactor

docker/Dockerfile, frontend/src/views/Scan.vue
* Update nginx to `1.27.0-alpine3.19-slim` to keep redis at v7.2.4
=> Install redis instead of building in Dockerfile

backend/endpoints/responses/rom.py, backend/handler/filesystem/base_handler.py, backend/handler/filesystem/roms_handler.py, backend/handler/metadata/base_hander.py, backend/handler/metadata/igdb_handler.py, backend/handler/metadata/moby_handler.py
Improve efficiency on reusable regular expressions, by compiling them.
=> misc: Compile constant regular expressions

.trunk/trunk.yaml, backend/endpoints/forms/identity.py, backend/endpoints/responses/assets.py, backend/endpoints/responses/oauth.py, backend/endpoints/responses/platform.py, backend/endpoints/responses/rom.py, backend/endpoints/tests/test_identity.py, backend/handler/auth/middleware.py, backend/handler/auth/tests/test_auth.py, backend/handler/metadata/base_hander.py, backend/handler/metadata/igdb_handler.py, backend/handler/metadata/moby_handler.py, backend/handler/scan_handler.py, backend/models/user.py, backend/tasks/update_switch_titledb.py
Changes automatically made by
[`pyupgrade`](https://github.com/asottile/pyupgrade), using the `--py311-plus` flag, to be compatible with Python 3.11.
=> misc: Apply changes generated by pyupgrade

backend/endpoints/platform.py, backend/endpoints/sockets/scan.py
Fixed datetime serialization on scan socket
=> Fix socket scan logs

backend/handler/database/stats_handler.py
Add query that calculates total filesize statistic, currently hardcoded to zero.
=> fix: Add implementation for total filesize statistic

docker/Dockerfile
Fix recently introduced `FromAsCasing` [1] Docker build check.
[1] https://docs.docker.com/reference/build-checks/from-as-casing/
=> misc: Fix FromAsCasing warning during Docker build

backend/endpoints/rom.py, poetry.lock, pyproject.toml
Replace use of synchronous `stream_zip` implementation, with `async_stream_zip`. [1]
[1] https://stream-zip.docs.trade.gov.uk/async-interface/
=> misc: Use async interface for stream-zip

backend/endpoints/sockets/scan.py, frontend/src/components/Gallery/FabOverlay.vue
Did a bit of refactoring while in there, but the fix here is that scan type should be `quick`, not `partial`.
=> [ROMM-1018] Fix scanning selected roms

frontend/src/components/Gallery/AppBar/Platform/FirmwareDrawer.vue
=> [ROMM-1020] Fix firmware pagination on mount

frontend/src/layouts/Administration/Tasks.vue
adds missing space brfore cron in administration/tasks
=> Fix tyo in feontend

frontend/src/components/Gallery/FabOverlay.vue, frontend/src/components/common/NewVersion.vue
https://vuetifyjs.com/en/api/v-overlay/#props-close-on-back
Fixes #1031
=> [ROMM-1031] Remove persistent overlay prevents back navigation

frontend/src/components/common/Navigation/HomeBtn.vue
Added link to home button
fixed #1052
=> Added link to home button

frontend/src/components/Gallery/FabOverlay.vue, frontend/src/components/common/NewVersion.vue
Fab is broken in the last version in the gallery non-list views
Also removed overlays to fix browser back issues
=> fix: fab overlay fixed

frontend/src/views/Login.vue, frontend/src/views/Setup.vue
Fixed to white + shadow text on setup wizard when white theme is selected
=> fix: Readable setup text on white theme

frontend/src/components/common/RommIso.vue
=> Fix home icon size on safari/ios

frontend/src/components/common/Game/Card/Base.vue, frontend/src/components/common/Platform/Card.vue, frontend/src/layouts/Dashboard/Recent.vue, frontend/src/views/Gallery/Collection.vue, frontend/src/views/Gallery/Platform.vue
Adds support to open links to Games and Platforms in a new tab if you are holding the cmd/ctrl key
I may be missing some; please let me know if so
=> feat(UX) - Allow links to open in a new tab

frontend/src/components/common/Game/Dialog/EditRom.vue
=> [ROMM-1113] Add file path in rom edit window

.trunk/trunk.yaml, frontend/src/components/Gallery/AppBar/Platform/Base.vue, frontend/src/components/common/Game/AdminMenu.vue, frontend/src/components/common/Game/Card/ActionBar.vue, frontend/src/components/common/UploadInProgress.vue
Tweaked a couple of little UI details
=> Microfixes to game cards UI

frontend/src/components/common/Game/Table.vue
=> [ROMM-1150] Fix multi select in table view

.vscode/tasks.json, backend/handler/metadata/igdb_handler.py, frontend/src/components/Administration/Users/Dialog/EditUser.vue, frontend/src/components/Details/Notes.vue, frontend/src/components/Details/Saves.vue, frontend/src/components/Details/States.vue, frontend/src/components/Gallery/AppBar/Platform/FirmwareDrawer.vue, frontend/src/components/Management/Dialog/DeletePlatformBinding.vue, frontend/src/components/common/Collection/Dialog/CreateCollection.vue, frontend/src/components/common/Collection/Dialog/EditCollection.vue, frontend/src/components/common/Collection/Dialog/RemoveRoms.vue, frontend/src/components/common/Game/AdminMenu.vue, frontend/src/components/common/Game/Dialog/MatchRom.vue, frontend/src/components/common/Game/FavBtn.vue, frontend/src/components/common/RDialog.vue, frontend/src/components/common/SearchCover.vue, frontend/src/services/api/rom.ts, frontend/src/views/GameDetails.vue, frontend/src/views/Home.vue
Also ran trunk on a bunch of files which auto formatted them.
=> [ROMM-1123] Limit returned roms to 2500

backend/main.py
=> [ROMM-1165] set docs and recod paths

DEVELOPER_SETUP.md
I wanted to start work on implementing OpenID Connect and got nasty errors when trying to install the dev setup on Arch Linux.
Here is what helped :smile:
=> chore(README): Update dev instructions for Arch Linux users

README.md
Readme GIFs preview updated with the redesigned UI
=> docs: Updated readme preview

.vscode/tasks.json, backend/config/config_manager.py, backend/endpoints/config.py, backend/handler/filesystem/tests/test_fs.py, frontend/src/components/Management/Dialog/CreateExclusion.vue, frontend/src/components/Management/Dialog/CreatePlatformVersion.vue, frontend/src/components/Management/ExcludedCard.vue, frontend/src/components/common/Game/Dialog/EditRom.vue, frontend/src/layouts/Management/Excluded.vue, frontend/src/services/api/config.ts, frontend/src/stores/config.ts, frontend/src/types/emitter.d.ts
Added config exclusion endpoints:
- add exclusion
- delete exclusion
Enabled ``add``/``remove`` buttons for exclusions in the webUI
=> feat: Enable editable exclusions from webUI

backend/endpoints/rom.py
This filename error same like
https://github.com/rommapp/romm/pull/872
=> Update rom.py to Fix Filename error

backend/endpoints/sockets/scan.py
=> [ROMM-1292] Log when db entries are purged

backend/adapters/services/igdb_types.py
Add more typehints for IGDB entities, including `GameTimeToBeat`.
=> misc: Add more IGDB typehints

backend/handler/metadata/igdb_handler.py
One of the only places we are still using the sync cache, can be easily changed to use the async one.
=> misc: Use async cache in IGDB handler

backend/handler/metadata/igdb_handler.py
The key `romm:twitch_token_expires_at` is not needed, as we already set an expiration time for the token key itself. If the token is still present in Redis, it is valid. If not, it means we either never fetched it, or it was too close to expiration.
With this change, fetching the Twitch token makes a single Redis call instead of two.
=> misc: Remove unneeded Redis key for Twitch token expiration

backend/utils/archive_7zip.py
=> misc: Remove print leftover in CallbackIO class

.github/workflows/build.yml, .github/workflows/pytest.yml, .github/workflows/trunk-check.yml, .github/workflows/typecheck.yml, backend/handler/scan_handler.py
Added a bunch of slugs to the existing list + bumped deprecated github actions to latest version before they stop working
=> Expand list of non-hashable platforms

frontend/src/components/common/Game/Table.vue
Fixed the ``check all`` checkbox in the table view in the gallery
Closes #1380
=> fix: toggle check all in gallery table view

README.md
* Smaller donation button
* Install instructions now refer to the quick start guide
=> December README update

frontend/src/utils/index.ts
=> [ROMM-1432] Make neogeo aes and mvs games playable in emulatorjs

backend/decorators/auth.py, backend/endpoints/collections.py, backend/endpoints/configs.py, backend/endpoints/feeds.py, backend/endpoints/firmware.py, backend/endpoints/platform.py, backend/endpoints/raw.py, backend/endpoints/rom.py, backend/endpoints/saves.py, backend/endpoints/screenshots.py, backend/endpoints/search.py, backend/endpoints/states.py, backend/endpoints/tasks.py, backend/endpoints/tests/test_oauth.py, backend/endpoints/user.py, backend/handler/auth/base_handler.py, backend/handler/auth/constants.py, backend/handler/auth/tests/test_auth.py, backend/main.py, backend/models/tests/test_user.py, backend/models/user.py
This simplifies avoiding circular imports when trying to use auth handlers.
=> misc: Move auth constants to separate file

frontend/src/components/Details/VersionSwitcher.vue
=> [ROMM-1447] Add revision to formatTitle for version switcher

backend/endpoints/responses/rom.py, backend/models/rom.py, frontend/src/__generated__/models/DetailedRomSchema.ts, frontend/src/__generated__/models/RomSchema.ts, frontend/src/__generated__/models/SimpleRomSchema.ts, frontend/src/components/Details/Title.vue, frontend/src/components/common/Game/FavBtn.vue, frontend/src/components/common/Game/Table.vue
=> [ROMM-1433] Rework columns in table view

frontend/src/components/Details/ActionBar.vue, frontend/src/components/common/Game/Card/ActionBar.vue, frontend/src/components/common/Game/Table.vue
If a platform slug exists in `PLATFORMS_VERSIONS`, use the mapped platform to determine if the game is playable.
Fixes #1273
=> [ROMM-1273] Use platform versions to check if game playable

frontend/src/locales/en_GB/rom.json, frontend/src/locales/en_US/rom.json
=> fix: English translation value for "collections"

poetry.lock, pyproject.toml
`pyinstrument` for code profiling. `memray` for memory profiling.
=> misc: Add useful profiling tools to dev dependencies

backend/endpoints/rom.py
=> [ROMM-1522] Stop trying to set last_played from UI

frontend/src/components/Details/Info/GameInfo.vue
=> [ROMM-1482] Display game summary with mdeditor

frontend/src/components/Details/Personal.vue, frontend/src/utils/index.ts
=> [ROMM-1517] Use rating for dufficulty

frontend/src/components/Gallery/FabOverlay.vue, frontend/src/components/Gallery/Skeleton.vue, frontend/src/components/common/Collection/Dialog/RemoveRoms.vue, frontend/src/components/common/Game/AdminMenu.vue, frontend/src/components/common/RSection.vue, frontend/src/locales/de_DE/rom.json, frontend/src/locales/en_GB/rom.json, frontend/src/locales/en_US/rom.json, frontend/src/locales/es_ES/rom.json, frontend/src/locales/fr_FR/rom.json, frontend/src/locales/ko_KR/rom.json, frontend/src/locales/pt_BR/rom.json, frontend/src/locales/ru_RU/rom.json, frontend/src/locales/zh_CN/rom.json, frontend/src/views/Gallery/Collection.vue, frontend/src/views/Gallery/Platform.vue, frontend/src/views/Gallery/Search.vue
Added add/remove to/from collection to the rom admin menu
=> feat: added remove and add collection to rom admin menu

backend/handler/filesystem/roms_handler.py
* Wrap hash calc in a `try/catch` to stop scan from crashing
* Set hashes to empty string if cannot be calculated
Fixes #1588
=> [ROMM-1588] Skip hash calc on file not found/permission erros

frontend/src/__generated__/index.ts, frontend/src/__generated__/models/Body_add_collection_api_collections__post.ts, frontend/src/__generated__/models/Body_add_firmware_api_firmware__post.ts, frontend/src/__generated__/models/Body_add_saves_api_saves__post.ts, frontend/src/__generated__/models/Body_add_screenshots_api_screenshots__post.ts, frontend/src/__generated__/models/Body_add_states_api_states__post.ts
Changes generated by `openapi-typescript-codegen` when running `npm run generate`.
=> misc: Update code generated by openapi-typescript-codegen

backend/endpoints/responses/collection.py, backend/models/collection.py, frontend/src/__generated__/models/CollectionSchema.ts, frontend/src/__generated__/models/VirtualCollectionSchema.ts, frontend/src/components/common/Collection/Card.vue, frontend/src/components/common/Collection/RAvatar.vue, frontend/src/stores/collections.ts
This PR sets `is_virtual` explicitly on real and virtual collection, among a few other small improvements.
=> [HOTFIX] Define virtual collections correctly

frontend/src/components/common/Collection/Dialog/RemoveRoms.vue
Remove from collection only worked in collections view.
=> fix: Remove from collection dialog

backend/adapters/services/igdb_types.py, backend/handler/metadata/igdb_handler.py, frontend/src/components/common/Game/AdminMenu.vue
This PR updated the field we fetch from IGDB API based on their API changes
[IGDB migration notes](https://api-docs.igdb.com/#migration-enums-to-tables)
=> misc: migrate IGDB API fields to new version

backend/endpoints/feeds.py
=> misc: Use FRONTEND_RESOURCES_PATH setting in missing places

backend/handler/metadata/ss_handler.py
* Fix moon's issue with empty `companies` by wrapping in `pydash.compact`
* Refactor fields into generators for easier reading
=> Hotfix ss metadata

.trunk/trunk.yaml, backend/alembic/versions/0034_virtual_collections_db_view.py, backend/alembic/versions/0035_screenscraper.py
=> [HOTFIX] Fix collections migration in both directions

backend/endpoints/responses/collection.py, frontend/src/__generated__/models/CollectionSchema.ts, frontend/src/services/api/collection.ts, frontend/src/utils/index.ts
* Set `url_cover` as nullable on collections
* Calculate webgl support once for faster rendering of action menu
=> [HOTFIX] Calculate gl support once on load

frontend/src/locales/ja_JP/common.json, frontend/src/locales/ja_JP/emptyStates.json, frontend/src/locales/ja_JP/rom.json
Fixed some errors in the Japanese translation.
=> Fixed translation to Japanese

backend/endpoints/rom.py
In the event the ROM is moved in the filesystem by an update via the UI, we should also update the `rom.files` to point to the updated location. This can also be fixed by running a metadata update or quick scan.
=> [ROMM-1739] Update RomFile when rom fs changes

.trunk/trunk.yaml, frontend/src/components/Gallery/AppBar/Platform/PlatformInfoDrawer.vue, frontend/src/components/Settings/UserInterface/Interface.vue, frontend/src/components/common/Game/Dialog/UploadRom.vue, frontend/src/locales/de_DE/platform.json, frontend/src/locales/en_GB/platform.json, frontend/src/locales/en_US/platform.json, frontend/src/locales/es_ES/platform.json, frontend/src/locales/fr_FR/platform.json, frontend/src/locales/ja_JP/platform.json, frontend/src/locales/ko_KR/platform.json, frontend/src/locales/pt_BR/platform.json, frontend/src/locales/ru_RU/platform.json, frontend/src/locales/zh_CN/platform.json
Added aspect ratio option of 16:11 for game covers
=> feat: Added 16:11 aspect ratio for covers

backend/endpoints/responses/platform.py, backend/handler/database/stats_handler.py, backend/models/platform.py, frontend/src/__generated__/models/PlatformSchema.ts, frontend/src/components/Gallery/AppBar/Platform/PlatformInfoDrawer.vue, frontend/src/locales/de_DE/common.json, frontend/src/locales/de_DE/platform.json, frontend/src/locales/en_GB/common.json, frontend/src/locales/en_GB/platform.json, frontend/src/locales/en_US/common.json, frontend/src/locales/en_US/platform.json, frontend/src/locales/es_ES/common.json, frontend/src/locales/es_ES/platform.json, frontend/src/locales/fr_FR/common.json, frontend/src/locales/fr_FR/platform.json, frontend/src/locales/ja_JP/common.json, frontend/src/locales/ja_JP/platform.json, frontend/src/locales/ko_KR/common.json, frontend/src/locales/ko_KR/platform.json, frontend/src/locales/pt_BR/common.json, frontend/src/locales/pt_BR/platform.json, frontend/src/locales/ru_RU/common.json, frontend/src/locales/ru_RU/platform.json, frontend/src/locales/zh_CN/platform.json
Also a bit of cleanup and refactoring while I'm at it.
Fixes #1761
=> [ROMM-1761] Show platform disk size in sidebar

.github/workflows/test-build.yml
Github action that'll push/re-push an image to the [testing repo on Docker Hub](https://hub.docker.com/repository/docker/rommapp/romm-testing/general). Just pass in a tag!
=> Add github action to build experimental docker images

frontend/src/components/common/Navigation/PlatformsDrawer.vue
Fixed platform drawer on mobile
=> Hotfix: Platform drawer

backend/endpoints/rom.py, backend/models/rom.py
=> [ROMM-1795] Dont generate m3u file if folder already has one

frontend/src/components/Details/Info/GameInfo.vue
=> [ROMM-1764] Fix seeing zoomed screenshots

frontend/src/locales/it_IT/common.json
<sup>Fixed typo in common.json it_IT.</sup>
**Checklist**
=> Fixed typo in common.json it_IT

frontend/src/components/Gallery/AppBar/common/CharIndexBar.vue, frontend/src/components/Gallery/FabOverlay.vue, frontend/src/components/Gallery/LoadMoreBtn.vue, frontend/src/styles/scrollbar.css
- Improved and fixed CharIndexBar layout and fab buttons
- Added ``to top`` fab on table view
- Increased scrollbars width
**Checklist**
=> fix: Fixed and improved gallery layout

backend/endpoints/saves.py, backend/endpoints/states.py, frontend/src/services/api/save.ts, frontend/src/services/api/state.ts, frontend/src/views/Player/EmulatorJS/utils.ts
With this change, the screenshots of saves will also be updated, reducing confusion for users who might otherwise think their save didn't work just because the image didn't change. (me 😅)
**Checklist**
- I'm unable to do it
=> Update screenshots of saves when saving

.trunk/trunk.yaml, backend/adapters/services/rahasher.py, backend/alembic.ini, backend/alembic/env.py, backend/config/config_manager.py, backend/endpoints/collections.py, backend/endpoints/firmware.py, backend/endpoints/platform.py, backend/endpoints/rom.py, backend/endpoints/saves.py, backend/endpoints/screenshots.py, backend/endpoints/search.py, backend/endpoints/sockets/scan.py, backend/endpoints/states.py, backend/handler/auth/base_handler.py, backend/handler/filesystem/assets_handler.py, backend/handler/filesystem/firmware_handler.py, backend/handler/filesystem/resources_handler.py, backend/handler/redis_handler.py, backend/handler/scan_handler.py, backend/logger/formatter.py, backend/logger/logger.py, backend/scheduler.py, backend/watcher.py, backend/worker.py, docker/Dockerfile, docker/build_local_image.sh, docker/gunicorn/logging.conf, docker/init_scripts/init, docker/nginx/default.conf
This PR handles correctly the background processes to reduce RAM usage in the docker init script.
Also cleans and unifies the logs for every process
**Checklist**
=> fix: Optimize RAM usage

backend/handler/database/roms_handler.py, backend/handler/tests/conftest.py, frontend/src/components/common/Notifications/Notification.vue
When not filtering by hidden games, we should always filter out hidden games (when user is provided).
Fixes #1895 
**Checklist**
=> [ROMM-1895] Fix hiding hidden roms in lists

frontend/src/components/common/Navigation/MainAppBar.vue, frontend/src/stores/playing.ts, frontend/src/views/Player/EmulatorJS/Base.vue, frontend/src/views/Player/EmulatorJS/Player.vue
This PR is an attempt to fix te iOS issue that makes impossible to play fullscreen
**Checklist**
=> fix: iOS full screen play

backend/logger/log_middleware.py, backend/logger/logger.py, backend/main.py, poetry.lock, pyproject.toml
This PR unifies the uvicorn logs when RomM is launched in dev mode.
**Checklist**
=> feat: Unify uvicorn logs

backend/adapters/services/steamgriddb_types.py, backend/endpoints/feeds.py, backend/endpoints/responses/identity.py, backend/endpoints/responses/rom.py, backend/endpoints/search.py, backend/handler/auth/base_handler.py, backend/handler/database/collections_handler.py, backend/handler/database/firmware_handler.py, backend/handler/database/platforms_handler.py, backend/handler/database/roms_handler.py, backend/handler/database/saves_handler.py, backend/handler/database/screenshots_handler.py, backend/handler/database/states_handler.py, backend/handler/database/users_handler.py, backend/tools/xml_diagnostics.py, backend/utils/archive_7zip.py
Command applied:
```
find ./backend/ -type f -name "*.py" -exec pyupgrade --py312-plus {} \;
```
**Checklist**
=> misc: Apply pyupgrade changes for Python 3.12 compatibility

backend/endpoints/platform.py
- Add type annotations for FastAPI query, and path parameters.
- Add type annotations for request body content.
- Update docstrings to clarify endpoint functionality, and remove unnecessary details.
**Checklist**
=> misc: Improve API docs and annotations for platform endpoints

backend/adapters/services/mobygames.py, backend/adapters/services/retroachievements.py, backend/adapters/services/screenscraper.py, backend/handler/metadata/base_hander.py, backend/handler/metadata/igdb_handler.py, backend/handler/metadata/playmatch_handler.py, backend/handler/metadata/sgdb_handler.py, backend/handler/metadata/ss_handler.py, backend/handler/scan_handler.py
=> Hopefully last batch of metadata fixes

backend/endpoints/responses/platform.py, backend/models/platform.py, backend/models/rom.py, frontend/src/__generated__/models/PlatformSchema.ts, frontend/src/components/Details/Info/GameInfo.vue, frontend/src/components/Details/Title.vue, frontend/src/components/Gallery/AppBar/Platform/PlatformInfoDrawer.vue
=> I lied, more fixes

backend/handler/metadata/sgdb_handler.py, pyproject.toml, uv.lock
Changed to fuzzy match on SGDB cover search when scanning for better results
**Checklist**
=> refactor: improve fuzzy matching in SGDBBaseHandler for game search

backend/endpoints/raw.py
=> [HOTFIX] Fix downloading saves from asset endpoint

backend/endpoints/collections.py, backend/endpoints/rom.py, backend/handler/filesystem/base_handler.py, backend/handler/filesystem/resources_handler.py, backend/handler/filesystem/tests/test_resources_handler.py, backend/handler/metadata/igdb_handler.py
=> [HOTFIX] Fix uploading cover art manually

frontend/src/utils/index.ts
=> Adjust layout width calculation for improved responsiveness

README.md
=> fix: Gallery app bar layout

backend/handler/filesystem/roms_handler.py, backend/handler/tests/cassettes/test_fastapi/test_scan_rom.yaml
=> Use validate_path for getting rom_files

docker/init_scripts/init
Display RomM version in the docker startup logs
**Checklist**
=> feat: Display version information in the banner

backend/handler/filesystem/base_handler.py
=> [ROMM-2114] Fix using symlinks on volumes

backend/handler/metadata/igdb_handler.py, backend/handler/metadata/ss_handler.py, backend/utils/generate_supported_platforms.py
=> Group generated platforms by slug and filter by name

frontend/src/locales/de_DE/play.json, frontend/src/locales/en_GB/play.json, frontend/src/locales/en_US/play.json, frontend/src/locales/es_ES/play.json, frontend/src/locales/fr_FR/play.json, frontend/src/locales/it_IT/play.json, frontend/src/locales/ja_JP/play.json, frontend/src/locales/ko_KR/play.json, frontend/src/locales/pt_BR/play.json, frontend/src/locales/ro_RO/play.json, frontend/src/locales/ru_RU/play.json, frontend/src/locales/zh_CN/play.json, frontend/src/views/Player/RuffleRS/Base.vue
=> [ROMM-1230] Add background color picker to ruffle

frontend/src/components/common/Navigation/CollectionsBtn.vue, frontend/src/components/common/Navigation/PlatformsBtn.vue, frontend/src/components/common/Navigation/SearchBtn.vue, frontend/src/components/common/Navigation/UploadBtn.vue
<sup>Some UI component translation use current existing key.</sup>
**Checklist**
=> Some UI component translation.

backend/config/config_manager.py, backend/handler/filesystem/base_handler.py
=> [ROMM-2163] Fix excluding single roms without extensions

backend/handler/filesystem/resources_handler.py, frontend/src/composables/use-auto-scroll.ts, frontend/src/views/Scan.vue
Also fixes storing RA badges when already stored.
**Checklist**
=> Scroll to window bottom on scan

docker/Dockerfile, frontend/src/views/Player/RuffleRS/Base.vue
Upgrade Ruffle to `v2025-08-14`.
**Checklist**
=> misc: Upgrade Ruffle to v2025-08-14

backend/endpoints/responses/search.py, backend/endpoints/search.py, frontend/src/__generated__/models/SearchRomSchema.ts, frontend/src/components/common/Game/Card/Base.vue, frontend/src/components/common/Game/Dialog/MatchRom.vue
Plus fetch SGDB cover art for top 5 results (can be selected in second step)
**Checklist**
=> Normalize result names for better merging in search

backend/handler/database/roms_handler.py
=> [ROMM-2274] Use platform_id in group_by_meta_id

backend/alembic/versions/0050_firmware_add_is_verified.py, backend/endpoints/firmware.py, backend/endpoints/sockets/scan.py, backend/handler/database/base_handler.py, backend/handler/database/collections_handler.py, backend/handler/database/platforms_handler.py, backend/handler/database/roms_handler.py, backend/handler/metadata/playmatch_handler.py, backend/models/firmware.py
More database optimization 🐎 
* Converts `is_verified` from a computed property to a database column with migration
* Adds `noload()` and `joinedload()` options to ORM queries to prevent excessive data loading
* Only print single SQL commands when echo is enabled
**Checklist**
=> DB query micro optimizations

backend/alembic/versions/0050_firmware_add_is_verified.py
Tested on both postgres and mariadb locally, and both worked as expected.
Fixes #2317 
**Checklist**
=> [ROMM-2317] Fix postgres migration firmware is_verified

.devcontainer/devcontainer.json, docker-compose.yml, env.template, frontend/package-lock.json, frontend/package.json, frontend/vite.config.js
This PR allows running the development server in HTTPS mode, which would (in the future) let us run things like web workers or WASM threads.
**Checklist**
=> Run vite dev server with HTTPS enabled

frontend/src/components/Home/Collections.vue, frontend/src/views/Gallery/Collection/BaseCollection.vue, frontend/src/views/Gallery/Platform.vue, frontend/src/views/Gallery/Search.vue, frontend/src/views/Settings/LibraryManagement.vue
=> Replace window scroll listeners with reactive useWindowScroll

frontend/src/components/Home/Collections.vue, frontend/src/views/Gallery/Collection/BaseCollection.vue, frontend/src/views/Gallery/Platform.vue, frontend/src/views/Gallery/Search.vue, frontend/src/views/Settings/LibraryManagement.vue
=> Replace useWindowScroll with useScroll on document body

frontend/src/components/common/Game/Card/ActionBar.vue, frontend/src/components/common/Game/Card/Base.vue, frontend/src/components/common/Game/PlayBtn.vue, frontend/src/views/Gallery/Collection/BaseCollection.vue, frontend/src/views/Gallery/Platform.vue, frontend/src/views/Gallery/Search.vue
* Recalculate `isEmulationSupported` in the ActionBar component
* Wrap `isWebpEnabled` in a `computed` to memoize
* Use `rom.id` as keys for cards in gallery/search
**Checklist**
=> Performance fixes for gallery slowdown on card hover

backend/handler/scan_handler.py
An empty array entry would overwrite one with screenshots, so we set that field manually.
**Checklist**
=> [ROMM-2039] Add special case for screenshots during scan

frontend/src/components/common/Game/PlayBtn.vue, frontend/src/console/Layout.vue, frontend/src/console/constants/platforms.ts, frontend/src/console/views/Play.vue
Can't reload and stay in fullscreen in console mode, so kill support for PSP/DOS and don't reload.
**Checklist**
=> Remove PSP and DOS support in console mode

backend/endpoints/collections.py, backend/endpoints/firmware.py, backend/endpoints/platform.py, backend/endpoints/rom.py, backend/endpoints/saves.py, backend/endpoints/states.py, backend/endpoints/user.py
Add more detailed descriptions for Delete endpoints.
**Checklist**
=> misc: Improve API docs for Delete endpoints

backend/endpoints/sockets/scan.py, backend/tasks/scheduled/update_launchbox_metadata.py
=> Revert "[HOTFIX] Limit memory usage of launchbox metadata update"

frontend/src/views/Player/EmulatorJS/Base.vue
=> [ROMM-2440] Remove sidebar during emulatorjs play

.trunk/trunk.yaml, backend/endpoints/responses/search.py, backend/endpoints/search.py, backend/handler/metadata/flashpoint_handler.py, backend/handler/metadata/launchbox_handler.py, frontend/src/__generated__/models/SearchRomSchema.ts, frontend/src/components/common/Game/Card/Base.vue, frontend/src/components/common/Game/Card/Sources.vue, frontend/src/components/common/Game/Dialog/MatchRom.vue
This PR fixes the missed addition of launchbox to the search endpoint and manual match dialog.
**Checklist**
=> Add launchbox to manual match window

backend/handler/filesystem/resources_handler.py
=> [ROMM-2467] Uncompress gzipped images

backend/endpoints/rom.py, backend/handler/scan_handler.py, frontend/src/services/api/rom.ts
=> [HOTFIX] Set url_cover on artwork upload

backend/endpoints/rom.py, frontend/src/__generated__/models/CustomLimitOffsetPage_SimpleRomSchema_.ts, frontend/src/components/Details/BackgroundHeader.vue, frontend/src/stores/roms.ts
=> [ROMM-2476] Add new index for rom-to-rom navigation

backend/endpoints/search.py
Forgot to add HLTB to manual match/search results.
Fixes #2492 
**Checklist**
=> [ROMM-2492] Add hltb to search reults

backend/handler/metadata/base_handler.py, backend/tests/handler/metadata/test_base_handler.py
=> [ROMM-2516] Fix comma article pattern regex

backend/endpoints/feeds.py, backend/endpoints/responses/feeds.py
Fixed tinfoil titledb shenanigans. Tested on my instance and is working!
=> Sanitize Tinfoil TitleDB via Pydantic v2 and use .model_dump()
